### ISSUE TITLE
Scikit-learn fails to build

### ISSUE THREAD

**Issue by sarocu** [indygreg/PyOxidizer#117]
TLDR; I am packaging up a scientific Python environment that requires SciPy. During the `pip install` for SciPy, PyOxidizer fails with the following gfortran-related error and stack trace:
```
    /usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/_fftpackmodule.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/zfft.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/drfft.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/zrfft.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/zfftnd.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src/dct.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src/dst.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/fortranobject.o -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0 -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/../../.. -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/../../.. -Lbuild/temp.macosx-10.9-x86_64-3.7 -ldfftpack -lfftpack -lgfortran -o build/lib.macosx-10.9-x86_64-3.7/scipy/fftpack/_fftpack.cpython-37m-darwin.so
    ld: library not found for -lSystem
    collect2: error: ld returned 1 exit status
    ld: library not found for -lSystem
    collect2: error: ld returned 1 exit status
    error: Command "/usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/_fftpackmodule.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/zfft.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/drfft.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/zrfft.o build/temp.macosx-10.9-x86_64-3.7/scipy/fftpack/src/zfftnd.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src/dct.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src/dst.o build/temp.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/fortranobject.o -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0 -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/../../.. -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/../../.. -Lbuild/temp.macosx-10.9-x86_64-3.7 -ldfftpack -lfftpack -lgfortran -o build/lib.macosx-10.9-x86_64-3.7/scipy/fftpack/_fftpack.cpython-37m-darwin.so" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sam/superplus/cli/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.b0f2d7fcc16f/python/install/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yb/3tr_nmc16ms3z33hx4czls0m0000gn/T/pip-install-6c5lqz4g/scipy/setup.py'"'"'; __file__='"'"'/private/var/folders/yb/3tr_nmc16ms3z33hx4czls0m0000gn/T/pip-install-6c5lqz4g/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yb/3tr_nmc16ms3z33hx4czls0m0000gn/T/pip-record-gve885pk/install-record.txt --single-version-externally-managed --compile --home=/private/var/folders/yb/3tr_nmc16ms3z33hx4czls0m0000gn/T/pip-target-g7aalc2n Check the logs for full command output.

thread 'main' panicked at 'error running pip', /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/pyoxidizer-0.1.3/src/pyrepackager/repackage.rs:1071:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: pyoxidizer::pyrepackager::repackage::resolve_python_packaging
   7: pyoxidizer::pyrepackager::repackage::resolve_python_resources
   8: pyoxidizer::pyrepackager::repackage::process_config
   9: pyoxidizer::projectmgmt::build_pyoxidizer_artifacts
  10: pyoxidizer::projectmgmt::build_project
  11: pyoxidizer::projectmgmt::run
  12: pyoxidizer::cli::run_cli
  13: pyoxidizer::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start_internal
  18: main
```

Context:
MacOS build: `build_target = "x86_64-apple-darwin"` using a Python distribution built with python-build-standalone (that successfully installs SciPy outside of PyOxidizer):
```
[[python_distribution]]
build_target = "x86_64-apple-darwin"
url = "https://github.com/sarocu/thingsandstuff/releases/download/0.1.0/cpython-3.7.4-macos-20190812T2357.tar.zst"
sha256 = "b0f2d7fcc16f896ce14abed70407617d0011611be970d4544fdbc00968a1b800"
```

Any insight?

**Comment by sarocu** [comment]
Update:
This appears to be an issue with environment variables, setting the following gets me a little further down the line:
```
export STATIC_DEPS=true
# OpenMP support:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
export LDFLAGS="$LDFLAGS -L/usr/local/opt/libomp/lib -lomp"
export DYLD_LIBRARY_PATH=/usr/local/opt/libomp/lib
```

And now scikit can find OpenMP and standard libraries but is still choking on finding architecture specific symbols:
```
ld: symbol(s) not found for architecture x86_64
    collect2: error: ld returned 1 exit status
    error: Command "/usr/local/bin/gfortran -Wall -g -L/usr/local/opt/libomp/lib -lomp build/temp.macosx-10.9-x86_64-3.7/scipy/cluster/_vq.o -L/usr/lib -L/usr/local/Cellar/gcc/9.2.0/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0 -L/usr/local/Cellar/gcc/9.2.0/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/../../.. -L/usr/local/Cellar/gcc/9.2.0/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/../../.. -Lbuild/temp.macosx-10.9-x86_64-3.7 -llapack -llapack -lblas -lblas -lgfortran -o build/lib.macosx-10.9-x86_64-3.7/scipy/cluster/_vq.cpython-37m-darwin.so" failed with exit status 1
```

Since I can install with the same Python interpreter locally, it would appear that this is related to environment variables from the host not making it into whatever subprocess that Rust is kicking off...

**Comment by sarocu** [comment]
Update:

I am able to successfully build an executable with SciPy and Scikit-learn - hoorary! - by using the `virtualenv` packaging rule and a virtualenv that was built using the target version of Python. 

However, a number of modules including Numpy require the use of `__file__` to import which isn't supported by PyOxidizer:
```bash
Traceback (most recent call last):
  File "sklearn.__check_build", line 44, in <module>
ModuleNotFoundError: No module named 'sklearn.__check_build._check_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sklearn", line 75, in <module>
  File "sklearn.__check_build", line 46, in <module>
  File "sklearn.__check_build", line 19, in raise_build_error
NameError: name '__file__' is not defined
```

Anyone got a hacky way of getting around it?

**Comment by sarocu** [comment]
closing this issue since now I'm facing the same problem outlined in #69
