### ISSUE TITLE
Not build in Windows10

### ISSUE THREAD

**Issue by CarmeloViavattene** [indygreg/PyOxidizer#126]
rustc 1.37.0 (eae3437df 2019-08-13)
pyoxidizer 0.4

writing packed Python module and resource data...
9869399 bytes of Python module data written to C:/Users/Carmelo/pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\py-modules
4 bytes of resources data written to C:/Users/Carmelo/pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python-resources
generating custom link library containing Python...
deriving custom config.c from 83 extension modules
compiling custom config.c to object file
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Brepro" "-I" "C:\\Users\\Carmelo\\AppData\\Local\\Temp\\libpython.49NXlGMowhoa" "-W4" "-std=c99" "-DNDEBUG" "-DPy_BUILD_CORE" "-FoC:/Users/Carmelo/pyapp\\build\\target\\x86_64-pc-windows-msvc\\debug\\pyoxidizer\\config.o" "-c" "C:\\Users\\Carmelo\\AppData\\Local\\Temp\\libpython.49NXlGMowhoa\\config.c"
cargo:warning=cl : warning della riga di comando D9002 : l'opzione sconosciuta '-std=c99' verrconfig.c
C:\Users\Carmelo\AppData\Local\Temp\libpython.49NXlGMowhoa\pytime.h(123): warning C4115: 'timeval': definizione di tipo denominato tra parentesi
thread '<unnamed>' panicked at 'failed printing to stdout: Windows stdio in console mode does not support writing non-UTF-8 byte sequences', src\libstd\io\stdio.rs:792:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'thread should not panic: Any', src\libcore\result.rs:999:5

**Comment by CarmeloViavattene** [comment]
setting RUST_BACKTRACE = 1

writing packed Python module and resource data...
9869399 bytes of Python module data written to C:/Users/Carmelo/pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\py-modules
4 bytes of resources data written to C:/Users/Carmelo/pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python-resources
generating custom link library containing Python...
deriving custom config.c from 83 extension modules
compiling custom config.c to object file
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Brepro" "-I" "C:\\Users\\Carmelo\\AppData\\Local\\Temp\\libpython.xSmIlVBlYRR8" "-W4" "-std=c99" "-DNDEBUG" "-DPy_BUILD_CORE" "-FoC:/Users/Carmelo/pyapp\\build\\target\\x86_64-pc-windows-msvc\\debug\\pyoxidizer\\config.o" "-c" "C:\\Users\\Carmelo\\AppData\\Local\\Temp\\libpython.xSmIlVBlYRR8\\config.c"
cargo:warning=cl : warning della riga di comando D9002 : l'opzione sconosciuta '-std=c99' verrconfig.c
C:\Users\Carmelo\AppData\Local\Temp\libpython.xSmIlVBlYRR8\pytime.h(123): warning C4115: 'timeval': definizione di tipo denominato tra parentesi
thread '<unnamed>' panicked at 'failed printing to stdout: Windows stdio in console mode does not support writing non-UTF-8 byte sequences', src\libstd\io\stdio.rs:792:9
stack backtrace:
   0: git_filter_source_repo
   1: git_filter_source_repo
   2: git_filter_source_repo
   3: git_filter_source_repo
   4: git_filter_source_repo
   5: git_filter_source_repo
   6: git_filter_source_repo
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: git_filter_source_repo
  12: <unknown>
  13: git_filter_source_repo
  14: git_filter_source_repo
  15: BaseThreadInitThunk
  16: RtlUserThreadStart
thread 'main' panicked at 'thread should not panic: Any', src\libcore\result.rs:999:5
stack backtrace:
   0: git_filter_source_repo
   1: git_filter_source_repo
   2: git_filter_source_repo
   3: git_filter_source_repo
   4: git_filter_source_repo
   5: git_filter_source_repo
   6: git_filter_source_repo
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: git_filter_source_repo
  19: git_filter_source_repo
  20: git_filter_source_repo
  21: <unknown>
  22: git_libgit2_version
  23: BaseThreadInitThunk
  24: RtlUserThreadStart

**Comment by CarmeloViavattene** [comment]
windows 10 italian

**Comment by CarmeloViavattene** [comment]
i reinstall pyoxidizer
