### ISSUE TITLE
pyglet from venv problem with __file__

### ISSUE THREAD

**Issue by 42sol-eu** [indygreg/PyOxidizer#127]
## script (__main__.py in helper module)
```
import pyglet

window = pyglet.window.Window()
image = pyglet.resource.image('kitten.png')

@window.event
def on_draw():
    window.clear()
    image.blit(0, 0)

pyglet.app.run()
```

## Error output

```
Traceback (most recent call last):
  File "pyglet", line 353, in __getattr__
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyglet", line 353, in __getattr__
AttributeError: 'NoneType' object has no attribute 'get_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyglet", line 353, in __getattr__
AttributeError: 'NoneType' object has no attribute 'get_script_home'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "helper.__main__", line 3, in <module>
  File "pyglet", line 359, in __getattr__
  File "pyglet.window", line 1877, in <module>
  File "pyglet.window.win32", line 60, in <module>
  File "pyglet.canvas", line 64, in <module>
  File "pyglet.app", line 165, in <module>
  File "pyglet.app.base", line 152, in __init__
  File "pyglet", line 359, in __getattr__
  File "pyglet.clock", line 125, in <module>
  File "pyglet.lib", line 60, in <module>
  File "pyglet", line 359, in __getattr__
  File "pyglet.resource", line 798, in <module>
  File "pyglet.resource", line 329, in __init__
  File "pyglet.resource", line 145, in get_script_home
  File "ntpath", line 526, in abspath
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
SystemError
error: cargo run failed
```
## NOTES: 
- this seems connected to calls like `path = os.path.dirname(os.path.abspath(main.__file__))`

**Comment by indygreg** [comment]
The code in `pyglet.resource` that is failing is:

```
    frozen = getattr(sys, 'frozen', None)
    meipass = getattr(sys, '_MEIPASS', None)
    if meipass:
        # PyInstaller
        return meipass
    elif frozen in ('windows_exe', 'console_exe'):
        return os.path.dirname(sys.executable)
    elif frozen == 'macosx_app':
        # py2app
        return os.environ['RESOURCEPATH']
    else:
        main = sys.modules['__main__']
        if hasattr(main, '__file__'):
            return os.path.dirname(os.path.abspath(main.__file__))
        else:
            if 'python' in os.path.basename(sys.executable):
                # interactive
                return os.getcwd()
            else:
                # cx_Freeze
                return os.path.dirname(sys.executable)
```

So I could point the finger at `pyglet` and say they need to teach `pyglet` to recognize PyOxidizer. But before I do that, I want to make PyOxidizer a bit more friendly when it comes to identifying itself and allowing package maintainers to customize PyOxidizer so it masquerades as other tools like PyInstaller.

**Comment by indygreg** [comment]
I just pushed a feature that adds `sys_frozen` and `sys_meipass` flags to `[[embedded_python_config]]`. If you enable both, `pyglet` may _just work_. Please give it a test!

**Comment by jayvdb** [comment]
I have a bit of experience with pyglet, and I am pretty sure it is going to be a nightmare getting it working.  It uses `__file__` , and it loads dlls/sos all over the place.  The result wont be a static binary without a huge undertaking.
