### ISSUE TITLE
importlib_metadata.PackageNotFoundError: importlib_metadata

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#140]
When building a package including importlib_metadata, it fails.

During the build
```console
...
package importlib_metadata-0.23-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "requires.txt", "top_level.txt"]
package more_itertools-7.2.0-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "top_level.txt"]
package zipp-0.6.0-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "requires.txt", "top_level.txt"]
```
resolved 4 embedded resource files across 2 packages: {
    "importlib_metadata.docs": {
        "changelog.rst",
        "index.rst",
        "using.rst",
    },
    "importlib_metadata.tests.data": {
        "example-21.12-py3-none-any.whl",
    },
}
```

```py
>>> import importlib_metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "importlib_metadata", line 547, in <module>
  File "importlib_metadata", line 509, in version
  File "importlib_metadata", line 482, in distribution
  File "importlib_metadata", line 187, in from_name
importlib_metadata.PackageNotFoundError: importlib_metadata
```

Could this be because its setup.py is
```
from setuptools import setup

setup(use_scm_version=True)
```

And setup.cfg includes `setup_requires=setuptools-scm`.

I tried adding setuptools-scm to the project first, and then it is added to the list
```
package importlib_metadata-0.23-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "requires.txt", "top_level.txt"]
package more_itertools-7.2.0-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "top_level.txt"]
package setuptools_scm-3.3.3-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "entry_points.txt", "installed-files.txt", "top_level.txt", "zip-safe"]
package zipp-0.6.0-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "requires.txt", "top_level.txt"]
```

The comment at https://github.com/indygreg/PyOxidizer/blob/f2ad172e69fd614d8cba58a467064ad018db098a/pyoxidizer/src/pyrepackager/fsscan.rs#L216 (`Ignore EGG-INFO directory..`) is possibly related.  Packaging metadata is quite important for a lot of Python code to run properly, and likely this is the same underlying problem with `pkg_resources`.

**Comment by anthrotype** [comment]
> Packaging metadata is quite important for a lot of Python code to run properly

indeed it is. Entry-points are defined in there, they can be used to load plugins:
https://importlib-metadata.readthedocs.io/en/latest/using.html#entry-points
https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins

> likely this is the same underlying problem with pkg_resources

Yes. In fact, pkg_resources also doesn't work with PyOxidizer (see https://github.com/indygreg/PyOxidizer/issues/134), and as the current issue shows also its replacement, `importlib_metadata`, does not...

What would the recommended workaround be, besides of course not using importlib_metadata or pkg_resources (hence giving up on dynamic plugin discovery)?

**Comment by anthrotype** [comment]
this doc https://importlib-metadata.readthedocs.io/en/latest/using.html#extending-the-search-algorithm explain how one could extend `importlib.metadata` search algorithm for package metadata that is not stored on the fille system.

> What this means in practice is that to support finding distribution package metadata in locations other than the file system, you should derive from Distribution and implement the load_metadata() method. Then from your finder, return instances of this derived Distribution in the find_distributions() method.

PyOxidizer could store all metadata for the pip-installed packages somewhere inside the binary, then define a custom `DistributionFinder` that returns custom `Distribution` objects that can load the metadata from this custom location, and register this custom finder in `sys.meta_path` where importlib.metadata searches for custom finders.

**Comment by indygreg** [comment]
Thank you for doing the research on the metadata APIs. It looks like we'll need to teach the built-in meta path importer some new tricks to support this API.

**Comment by indygreg** [comment]
I looked into implementing `find_distributions()`. However, I ran into enough issues with the documentation that I don't want to sink too much time into it before I get answers from the Python maintainers. I recorded my questions at https://bugs.python.org/issue38594.

**Comment by jayvdb** [comment]
Tracing through the [Zip & Egg tests](https://gitlab.com/python-devs/importlib_metadata/blob/master/importlib_metadata/tests/test_zip.py) may help us answer some of those questions. (looks to be almost identical to cpython's [`test_zip.py`](https://github.com/python/cpython/blob/master/Lib/test/test_importlib/test_zip.py).)

https://github.com/thought-machine/please/pull/764 seems to be tackling the same problem with PEX, and may have a working implementation which passes basic tests - might be good to share knowledge with. (https://github.com/facebook/buck also has some interesting PEX stuff happening internally)

https://github.com/pantsbuild/pex/blob/16cfd970cba2d9d85b966ca4e50cd23a6d024cdf/pex/finders.py and https://github.com/facebookincubator/xar/commit/b2501b03525fdc4ab720c4a9f45142a55b0a8d9c seems to be re-using the existing pkg_resources.find_distributions rather than creating its own.  If I read them correctly, they bundle pkg_resources (and markerlib) as a mandatory component, and then present their internal distributions as wheels/eggs.  Maybe PyOxidizer can provide Wheel subclasses as a container for the metadata.  The use of wheels in this way doesnt appear to be supported, c.f. https://github.com/pypa/packaging-problems/issues/244 which mentions PyOxidizer.

[setuptools "find_distributions"](https://github.com/pypa/setuptools/search?q=find_distributions&unscoped_q=find_distributions) may be relevant.

**Comment by jayvdb** [comment]
https://github.com/zopefoundation/z3c.autoinclude/blob/c80c37778b190188f986c1c0a544f220848ffba1/src/z3c/autoinclude/utils.py#L81 is another usage of `find_distributions`, which may help clarify how it may be used.

**Comment by layday** [comment]
One of the authors of `importlib.metadata` appears to have addressed the documentation deficiencies last month.

**Comment by indygreg** [comment]
I just rewrote the format that resources are embedded in binaries and I carved out room to denote package metadata in the embedded resources. It should now be possible to teach the packaging code to discover and include package distribution/metadata files and for the in-memory importer to expose the API so `importlib.metadata` and friends can read it.

**Comment by indygreg** [comment]
The `main` branch now has some support for `importlib.metadata`.

The resource scanning code should now properly recognize files in `.dist-info` and `.egg-info` directories as *package distribution resource* files. These files are exposed to Starlark and can be packaged, just like source and bytecode modules can. The files are encoded within the embedded resources blob, just like source and bytecode modules.

Support for packaging these files should be robust.

The custom module importer now provides a `find_distributions()` method that returns custom types that describe a distribution. However, they do not yet implement the complete API as defined by `importlib.metadata.Distribution`. See https://pyoxidizer.readthedocs.io/en/latest/packaging_importer.html#importlib-metadata-compatibility for details.

We could implement the full API. But it would be a lot of work. I'm inclined to get this current PyOxidizer release out the door then require Python 3.8 in the next release. At that point, we can use `importlib.metadata.Distribution` and implement our custom `Distribution` much more easily. So we're probably look at version 0.8 for full `importlib.metadata` support.
