### ISSUE TITLE
test subcommand

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#141]
It would be nice if pyozidizer had a test command that was the equivalent of `setup.py test` (I know setuptools is trying to kill it, and that it will only work for a subset of packages, but ~50% of the core packages provided by a Unix distro will support it.  And adding an equivalent of `setup.py pytest` would provide much higher compatibility)

A very useful part of Nuitka is that it can build Python packages as loadable shared libraries.  This means that each dependent package can then be tested using the normal test suite of the package, using whatever test runner is needed, such as nose or pytest, and the test runner doesnt need to have been compiled with Nuitka.  This doesnt guarantee that a standalone built with Nuitka would also pass the test suite of those packages, but it is a helpful smoke test to catch dependencies doing something strange in a new release which would break the standalone in a hard to QA / detect way.

I can achieve an even better result with PyOxidizer with some fiddling. e.g. the following relevant part of `pyoxidizer.toml`

```toml
[[packaging_rule]]
type = "pip-install-simple"
package = "pytz"

# Add tests which are not installed
[[packaging_rule]]
type = "package-root"
path = "/path/to/sourcetree/pytz-2019.3"
packages = ["pytz.tests"]
```

```py
$ /path/to/pytz
>>> import unittest
>>> unittest.main('pytz.tests.test_lazy')
.......................................
----------------------------------------------------------------------
Ran 39 tests in 0.010s

OK

$ /path/to/pytz
>>> import unittest
>>> unittest.main('pytz.tests.test_tzinfo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unittest.main", line 70, in __init__
  File "pytz.tests.test_tzinfo", line 40, in <module>
  File "pytz", line 172, in timezone
  File "pytz", line 198, in _case_insensitive_zone_lookup
  File "pytz.lazy", line 101, in _lazy
  File "pytz", line 1104, in <genexpr>
  File "pytz", line 114, in resource_exists
  File "pytz", line 95, in open_resource
NameError: name '__file__' is not defined
```

boom.  There is the failure in https://github.com/indygreg/PyOxidizer/issues/91 .

Roughly the same toml is needed for `appdirs`, excepting its tests are in a `test` package which isnt installed.

If that could be wrapped up into a test command, it would be easier to determine which packages are likely broken when built with PyOxidizer, and also provide a way to quickly verify that those bugs have been fixed.

https://github.com/indygreg/PyOxidizer/issues/122 gave me another idea -- it would be useful to be able to build an exe which has an entry point that is for the app CLI, but then run something like `USE_PYTHON_CLI=1 my_new_exe -m unittest` or similar to invoke a hidden CLI which is a close replica of the CPython cli, thereby getting better access into the internals of the built exe.

Attempting with nose failed due to https://github.com/indygreg/PyOxidizer/issues/139

Attempting with pytest failed due to https://github.com/indygreg/PyOxidizer/issues/140

**Comment by indygreg** [comment]
A new command to run tests is an interesting idea. But as you mentioned, we would need support for a `python`-like executable first or a way to embed test runners into the executable. I also think this is a good idea!

**Comment by jayvdb** [comment]
Having a runtime mode which is a `python`-like executable would be a useful addition on its own - even it is the only mode available in the built executable. It obviously wouldn't be complete at first, and probably never would be, but it will allow tests that use `[sys.executable, '-m', 'foo']` to test their CLI to pass, and most packages in distros need to use that style in their tests otherwise their tests will fail, and distro ppl usually have patches to fix these were necessary.

I don't see the benefit in embedding the test runners - those could be loaded via `PYTHONPATH` from outside the runtime, where they face less problems, and the eventual goal I have is to have a built exe from PyOxidizer that we can run extensive tests against - for each of the components inside of the built exe, so that it can be redistributed with confidence that it is correct.

For context, I already have done this per-package testing with Nuitka for a significant set of packages.  https://github.com/Nuitka/Nuitka/issues/522 (very few problems) and then also Nuitka on mingw+wine https://github.com/Nuitka/Nuitka/issues/537 (lots of problems, not much time invested in this).  I'd like to do the same for PyOxidizer (but that will require getting PyOxidizer packaged up for openSUSE).

**Comment by jayvdb** [comment]
Noting to self that getting PyOxidizer into openSUSE looks like it might not be too difficult with [282 crates](https://build.opensuse.org/project/show/devel:languages:rust:crates) already in the system, but Fedora has 820.  Sounds like it is worth investigating how many are missing from openSUSE; if too many, I might target Fedora first.
Other distro packaging systems might be quite hard.
There are only [56 librust packages in Debian](https://packages.debian.org/search?keywords=+librust&searchon=names&suite=stable&section=all).

**Comment by jayvdb** [comment]
`nose` works with
```toml
[[embedded_python_config]]
filesystem_importer = true
sys_paths = ['/usr/lib/python3.7/site-packages']
[[packaging_rule]]
type = "pip-install-simple"
package = "wcwidth"
```
repl:
```py
>>> nose.run(argv=['--verbose', 'wcwidth.tests.test_core'])
........
----------------------------------------------------------------------
Ran 8 tests in 0.002s

OK
```
`pytest` doesnt
```py
>>> os.environ['PYTEST_DISABLE_PLUGIN_AUTOLOAD'] = '1'
>>> pytest.main(['-vvvv', '--pyargs', 'wcwidth.tests.test_core'])
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.7.5, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- /path/to/exe
cachedir: .pytest_cache
rootdir: /home/jayvdb/pyox/nosetests
collected 0 items                                                                                                                                                                              

================================================================================= no tests ran in 0.00 seconds =================================================================================
ERROR: file or package not found: wcwidth.tests.test_core (missing __init__.py?)
```

**Comment by jayvdb** [comment]
`pytest` works if both `pytest` and the target test suite are on disk
```toml
[[packaging_rule]]
type = "pip-install-simple"
package = "backcall"
```
repl
```py
>>> import os, pytest
>>> os.environ['PYTEST_DISABLE_PLUGIN_AUTOLOAD'] = '1'
>>> pytest.main(['-vvvv', '/path/to/backcall-0.1.0/tests'])
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.7.5, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- /path/to/exe
cachedir: .pytest_cache
rootdir: /path/to/backcall-0.1.0
collected 4 items                                                                                                                                                                              

/path/to/backcall-0.1.0/test_callback_prototypes.py::test_all_args <- /path/to/backcall-0.1.0/tests/test_callback_prototypes.py PASSED [ 25%]
/path/to/backcall-0.1.0/test_callback_prototypes.py::test_some_args_kwonly <- /path/to/backcall-0.1.0/tests/test_callback_prototypes.py PASSED [ 50%]
/path/to/backcall-0.1.0/test_callback_prototypes.py::test_some_args_defaults <- /path/to/python-backcall/backcall-0.1.0/tests/test_callback_prototypes.py PASSED [ 75%]
/path/to/backcall-0.1.0/test_callback_prototypes.py::test_no_args <- /path/to/backcall-0.1.0/tests/test_callback_prototypes.py PASSED [100%]

=================================================================================== 4 passed in 0.07 seconds ===================================================================================
```

**Comment by jayvdb** [comment]
A rough idea on how to implement this.

There needs to be extra test dependencies, and I suggest that each packaging rule can have a different 'target', being "release", "debug" or "test".

Test dependencies would then be split into compiled modules and non-compiled modules.
Compiled test dependencies are added to the test version of the app, and non-compiled test dependencies would be put into a venv which is added to `sys_paths` (or added via `PYTHONPATH` (https://github.com/indygreg/PyOxidizer/issues/150)), and has its compiled modules removed if necessary to avoid them being loaded.

Then the test command would iterate through each package which was embedded, and attempt to find and run the tests for it.  This is easy where the module had the tests embedded with the package, such as `pytz.tests`, and if they can be invoked using `unittest` or `nose`.
I would then add a dictionary of packages mapped to paths for the tests of each package, letting the packager worry about fetching the correct tests and filling in the dictionary, and then run `pytest` on each of them.

The main feature I would want is the option of failing if a package doesnt have tests supplied, or explicitly marked as ignored.  My concern is that using PyOxidizer in CD is that a new dependency will slip in unnoticed, e.g. added by an indirect dependency, and some part of its codebase is incompatible with PyOxidizer, and users hit that code path by the tests of other packages do not.  Of course there is reasonable chance that the test suite of any dependency might not reach the incompatible code, but that can be mostly mitigated by having processes around choosing dependencies, and evaluation of unexpected dependencies added by other dependencies.

**Comment by jayvdb** [comment]
It would also be useful to support black box CLI tests written in a non-Python testing framework, in order to promote users creating new tests explicitly for the PyOxidized binary, distinct from any tests of the internals.  Using a rust cli testing framework for this would increase Python users exposure to rust tools, and possibly help grow confidence for them adding new features in rust instead of Python.

**Comment by jayvdb** [comment]
> Then the test command would iterate through each package which was embedded, and attempt to find and run the tests for it.

It would be nice if `pip download` is used, and the tarballs kept after the install phase, so that their test suite can be executed, if the sdist contained a test suite.  This leverages ongoing efforts by distros to have sdists contain tests, and would mean tests are available for most core packages, and then custom logic is only needed for packages which dont yet supply tests in the sdist (and that can be fixed upstream).

**Comment by AlJohri** [comment]
>A new command to run tests is an interesting idea. But as you mentioned, we would need support for a python-like executable first or a way to embed test runners into the executable.

Just noting here that this was addressed in #122.
