### ISSUE TITLE
LookupError: unknown encoding: uft-8

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#151]
LookupError: unknown encoding: uft-8
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'write failed: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x55c743ca9f7f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h2387d995b9073026
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55c743c9f577 - std::sys_common::backtrace::print::h73caeaceb668a47d
                               at src/libstd/sys_common/backtrace.rs:71
                               at src/libstd/sys_common/backtrace.rs:59
   2:     0x55c743c8ccd3 - std::panicking::default_hook::{{closure}}::h343883257d6a605e
                               at src/libstd/panicking.rs:197
   3:     0x55c743c8ca60 - std::panicking::default_hook::h896c5bc427faced8
                               at src/libstd/panicking.rs:211
   4:     0x55c743c8d3cf - std::panicking::rust_panic_with_hook::h64d2566eb4f32ecc
                               at src/libstd/panicking.rs:474
   5:     0x55c743c8cf61 - std::panicking::continue_panic_fmt::h0df69e4bd5d06d5b
                               at src/libstd/panicking.rs:381
   6:     0x55c743c8ce45 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x55c743cbf44c - core::panicking::panic_fmt::h02eac3544c403eac
                               at src/libcore/panicking.rs:85
   8:     0x55c7436376cd - core::result::unwrap_failed::hd52c795badf2a8e4
   9:     0x55c74364f7d6 - <pyoxidizer::pyrepackager::bytecode::BytecodeCompiler as core::ops::drop::Drop>::drop::h21b5befe375543f3
  10:     0x55c74369a79b - core::ptr::real_drop_in_place::h9dbf82fb4a7abccd
  11:     0x55c7436a54e5 - pyoxidizer::pyrepackager::repackage::resolve_python_resources::haa09dbd76b31ab09
  12:     0x55c7436ae648 - pyoxidizer::pyrepackager::repackage::process_config::h88ffe047af3b1b7e
  13:     0x55c74360f10c - pyoxidizer::projectmgmt::build_pyoxidizer_artifacts::hfafa87799770467b
  14:     0x55c74360fcd8 - pyoxidizer::projectmgmt::build_project::h7634666ab9de85df
  15:     0x55c743605fdb - pyoxidizer::cli::run_cli::h62f15a27bfab18dc
  16:     0x55c7435cf2b1 - pyoxidizer::main::h69324a3576e0a8a4
  17:     0x55c74367b3c2 - std::rt::lang_start::{{closure}}::haa857d16f6e1a157
  18:     0x55c743c8cde2 - std::panicking::try::do_call::h234aa24f95aba63f
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:293
  19:     0x55c743cac749 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  20:     0x55c743ca4c4f - std::rt::lang_start_internal::ha51c422a47a0dc3f
                               at src/libstd/panicking.rs:272
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  21:     0x55c7435cf7d4 - main
  22:     0x7f496cf6fe0a - __libc_start_main
  23:     0x55c74358e6c9 - _start
                               at ../sysdeps/x86_64/start.S:120
  24:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

**Comment by indygreg** [comment]
This looks like a fun bug. This feels like something that shouldn't occur. Most weird.
