### ISSUE TITLE
AttributeError: 'PyOxidizerFinder' object has no attribute 'get_filename'

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#160]
```py
ERROR: test_decorators (test.test_pyclbr.PyclbrTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.test_pyclbr", line 156, in test_decorators
    self.checkModule('test.pyclbr_input', ignore=['om'])
  File "test.test_pyclbr", line 67, in checkModule
    dict = pyclbr.readmodule_ex(moduleName)
  File "pyclbr", line 116, in readmodule_ex
  File "pyclbr", line 154, in _readmodule
  File "pyclbr", line 175, in _readmodule
AttributeError: 'PyOxidizerFinder' object has no attribute 'get_filename'
```
https://docs.python.org/3/library/importlib.html#importlib.abc.ExecutionLoader

**Comment by indygreg** [comment]
Yeah, our in-memory importer should probably implement this.
