### ISSUE TITLE
Mercurial on Windows fails to oxidize with `setup-py-install` type builds

### ISSUE THREAD

**Issue by mharbison72** [indygreg/PyOxidizer#191]
```
(pyO2_venv) C:\Users\Matt\hg3\hg_pyO2>pyoxidizer build
building artifacts because C:/Users/Matt/hg3/hg_pyO2\pyoxidizer.toml changed
processing config file C:/Users/Matt/hg3/hg_pyO2\pyoxidizer.toml
resolving Python distribution...
Python distribution available at C:/Users/Matt/hg3/hg_pyO2\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\cpython-3.7.5-windows-amd64-20191
025T0540.tar.zst
reading data from Python distribution...
distribution info: PythonDistributionMinimalInfo {
    flavor: "cpython",
    version: "3.7.5",
    os: "windows",
    arch: "x86_64",
    extension_modules: [
        "_abc",
        "_ast",
        "_asyncio",
        "_bisect",
        "_blake2",
        "_bz2",
        "_codecs",
        "_codecs_cn",
        "_codecs_hk",
        "_codecs_iso2022",
        "_codecs_jp",
        "_codecs_kr",
        "_codecs_tw",
        "_collections",
        "_contextvars",
        "_csv",
        "_ctypes",
        "_datetime",
        "_decimal",
        "_elementtree",
        "_functools",
        "_hashlib",
        "_heapq",
        "_imp",
        "_io",
        "_json",
        "_locale",
        "_lsprof",
        "_lzma",
        "_md5",
        "_msi",
        "_multibytecodec",
        "_multiprocessing",
        "_opcode",
        "_operator",
        "_overlapped",
        "_pickle",
        "_queue",
        "_random",
        "_sha1",
        "_sha256",
        "_sha3",
        "_sha512",
        "_signal",
        "_socket",
        "_sqlite3",
        "_sre",
        "_ssl",
        "_stat",
        "_string",
        "_struct",
        "_symtable",
        "_thread",
        "_tracemalloc",
        "_warnings",
        "_weakref",
        "_winapi",
        "array",
        "atexit",
        "audioop",
        "binascii",
        "builtins",
        "cmath",
        "errno",
        "faulthandler",
        "gc",
        "itertools",
        "marshal",
        "math",
        "mmap",
        "msvcrt",
        "nt",
        "parser",
        "pyexpat",
        "select",
        "sys",
        "time",
        "unicodedata",
        "winreg",
        "winsound",
        "xxsubtype",
        "zipimport",
        "zlib",
    ],
    libraries: [
        "libcrypto_static",
        "liblzma",
        "libssl_static",
        "sqlite3",
    ],
    py_module_count: 927,
}
compiling custom importlib modules to support in-memory importing
resolving Python resources (modules, extensions, resource data, etc)...
processing packaging rule: StdlibExtensionsPolicy(PackagingStdlibExtensionsPolicy { policy: "all" })
adding embedded extension module: _abc
adding embedded extension module: _ast
adding embedded extension module: _asyncio
adding embedded extension module: _bisect
adding embedded extension module: _blake2
adding embedded extension module: _bz2
adding embedded extension module: _codecs
adding embedded extension module: _codecs_cn
adding embedded extension module: _codecs_hk
adding embedded extension module: _codecs_iso2022
adding embedded extension module: _codecs_jp
adding embedded extension module: _codecs_kr
adding embedded extension module: _codecs_tw
adding embedded extension module: _collections
adding embedded extension module: _contextvars
adding embedded extension module: _csv
adding embedded extension module: _ctypes
adding embedded extension module: _datetime
adding embedded extension module: _decimal
adding embedded extension module: _elementtree
adding embedded extension module: _functools
adding embedded extension module: _hashlib
adding embedded extension module: _heapq
adding embedded extension module: _imp
adding embedded extension module: _io
adding embedded extension module: _json
adding embedded extension module: _locale
adding embedded extension module: _lsprof
adding embedded extension module: _lzma
adding embedded extension module: _md5
adding embedded extension module: _msi
adding embedded extension module: _multibytecodec
adding embedded extension module: _multiprocessing
adding embedded extension module: _opcode
adding embedded extension module: _operator
adding embedded extension module: _overlapped
adding embedded extension module: _pickle
adding embedded extension module: _queue
adding embedded extension module: _random
adding embedded extension module: _sha1
adding embedded extension module: _sha256
adding embedded extension module: _sha3
adding embedded extension module: _sha512
adding embedded extension module: _signal
adding embedded extension module: _socket
adding embedded extension module: _sqlite3
adding embedded extension module: _sre
adding embedded extension module: _ssl
adding embedded extension module: _stat
adding embedded extension module: _string
adding embedded extension module: _struct
adding embedded extension module: _symtable
adding embedded extension module: _thread
adding embedded extension module: _tracemalloc
adding embedded extension module: _warnings
adding embedded extension module: _weakref
adding embedded extension module: _winapi
adding embedded extension module: array
adding embedded extension module: atexit
adding embedded extension module: audioop
adding embedded extension module: binascii
adding embedded extension module: builtins
adding embedded extension module: cmath
adding embedded extension module: errno
adding embedded extension module: faulthandler
adding embedded extension module: gc
adding embedded extension module: itertools
adding embedded extension module: marshal
adding embedded extension module: math
adding embedded extension module: mmap
adding embedded extension module: msvcrt
adding embedded extension module: nt
adding embedded extension module: parser
adding embedded extension module: pyexpat
adding embedded extension module: select
adding embedded extension module: sys
adding embedded extension module: time
adding embedded extension module: unicodedata
adding embedded extension module: winreg
adding embedded extension module: winsound
adding embedded extension module: xxsubtype
adding embedded extension module: zipimport
adding embedded extension module: zlib
processing packaging rule: Stdlib(PackagingStdlib { optimize_level: 0, exclude_test_modules: true, include_source: false, include_resources: fals
e, install_location: Embedded })
processing packaging rule: WriteLicenseFiles(PackagingWriteLicenseFiles { path: "" })
processing packaging rule: SetupPyInstall(PackagingSetupPyInstall { path: "C:\\Users\\Matt\\hg", extra_env: {}, extra_global_arguments: [], optim
ize_level: 0, include_source: false, install_location: Embedded, excludes: [] })
installing modified distutils to C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages
modifying distutils/_msvccompiler.py for oxidation
modifying distutils/command/build_ext.py for oxidation
modifying distutils/unixccompiler.py for oxidation
python setup.py installing to C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\install
running install
running build
running build_mo
running build_py
running build_ext
running build_scripts
Traceback (most recent call last):
  File "setup.py", line 1717, in <module>
running build_hgexe
    **extra
  File "C:\Users\Matt\AppData\Roaming\Python\Python37\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\command\install.py", line 545, in run
    self.run_command('build')
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 576, in run
    self.run_command('build_hgexe')
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Matt\AppData\Local\Temp\pyoxidizer-setup-py-install.SObkNv9WbuoK\packages\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 729, in build_extensions
    sys.dllhandle, ctypes.byref(buf), size
AttributeError: module 'sys' has no attribute 'dllhandle'
thread 'main' panicked at 'error running setup.py', C:\Users\Matt\.cargo\registry\src\github.com-1ecc6299db9ec823\pyoxidizer-0.4.0\src\pyrepackag
er\packaging_rule.rs:1068:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jayvdb** [comment]
@mharbison72 , did you also try with the the pip rules?

I am not sure why `sys.dllhandle` wouldnt be set.  That sounds like a problem that needs solving, maybe it is a problem with the Windows Python's generated at https://github.com/indygreg/python-build-standalone/

**Comment by mharbison72** [comment]
> @mharbison72 , did you also try with the the pip rules?
> 
> I am not sure why `sys.dllhandle` wouldnt be set. That sounds like a problem that needs solving, maybe it is a problem with the Windows Python's generated at https://github.com/indygreg/python-build-standalone/

Pip install fails the same way.  I think you’re right though, because running `dir(sys)` on a simple repl build shows that `sys.dllhandle` is missing.

**Comment by indygreg** [comment]
There are a handful of ugly hacks in python-build-standalone to deal with `ctypes` wonkiness due to statically linked executables invalidating a lot of assumptions. For example, Python on Windows assumes there is a separate Python DLL from the EXE, which PyOxidizer doesn't do by default. Search for `dllhandle` in https://github.com/indygreg/python-build-standalone/blob/master/cpython-windows/build.py and read all about the hacks.

In this case, it is Mercurial's `setup.py` accessing `sys.dllhandle`. I think the proper thing to do is teach Mercurial to react gracefully when this attribute isn't set.

**Comment by mharbison72** [comment]
> In this case, it is Mercurial's `setup.py` accessing `sys.dllhandle`. I think the proper thing to do is teach Mercurial to react gracefully when this attribute isn't set.

Done, thanks for the pointer.
