### ISSUE TITLE
Packaged Borg Backup not finding Cython extensions

### ISSUE THREAD

**Issue by m3nu** [indygreg/PyOxidizer#215]
I'm trying to package package [Borg Backup](https://github.com/borgbackup/borg/) and seemingly hit a roadblock. Maybe someone spots an issue. Changed config (rest as in the template):

```
[[packaging_rule]]
type = "pip-install-simple"
package = "borgbackup"

[[embedded_python_run]]
mode = "module"
module = "borg.__main__"
```

Error when running binary:

```
Traceback (most recent call last):
  File "borg.archiver", line 41, in <module>
    from .archive import Archive, ArchiveChecker, ArchiveRecreater, Statistics, is_special
  File "borg.archive", line 22, in <module>
    from .cache import ChunkListEntry
  File "borg.cache", line 29, in <module>
    from .crypto.key import PlaintextKey
  File "borg.crypto.key", line 27, in <module>
    from ..platform import SaveFile
  File "borg.platform", line 18, in <module>
    from .posix import process_alive, local_pid_alive
ImportError: cannot import name 'process_alive' from 'posix' (unknown location)
```

While compiling, this line shows up, which should be good?

```
adding embedded built extension module: borg.platform.posix
```

Not sure why it's still not finding the module. The source file is a [pyx](https://github.com/borgbackup/borg/blob/master/src/borg/platform/posix.pyx) and the compiling is done in [`setup.py`](https://github.com/borgbackup/borg/blob/master/setup.py#L99) (in a standard way, I hope). Could those relativ imports be a problem?

**Comment by m3nu** [comment]
Just tried with the latest 0.8 version. Getting an error related to the bundled libraries again:

```
  = note: ld: warning: directory not found for option '-L/var/folders/g0/6wysw4qn6kl38gkv58jgkkfc0000gp/T/pyoxidizer-build-exe.VocmQjymviQK'
          Undefined symbols for architecture x86_64:
            "_blake2b_init", referenced from:
                ___pyx_pw_4borg_6crypto_9low_level_11blake2b_256 in libpyembed-97bb3fdb1f46bebc.rlib(libpython.220.o)
                ___pyx_pw_4borg_6crypto_9low_level_13blake2b_128 in libpyembed-97bb3fdb1f46bebc.rlib(libpython.220.o)
               (maybe you meant: _PyBlake2_blake2b_init_key, _PyBlake2_blake2b_init_param , _PyBlake2_blake2b_init )
            "_ZSTD_getFrameContentSize", referenced from:
                ___pyx_pw_4borg_8compress_4ZSTD_5decompress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_ZSTD_decompress", referenced from:
                ___pyx_pw_4borg_8compress_4ZSTD_5decompress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_blake2b_update", referenced from:
                ___pyx_pw_4borg_6crypto_9low_level_11blake2b_256 in libpyembed-97bb3fdb1f46bebc.rlib(libpython.220.o)
                ___pyx_pw_4borg_6crypto_9low_level_13blake2b_128 in libpyembed-97bb3fdb1f46bebc.rlib(libpython.220.o)
               (maybe you meant: _PyBlake2_blake2b_update)
            "_ZSTD_compress", referenced from:
                ___pyx_pw_4borg_8compress_4ZSTD_3compress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_ZSTD_compressBound", referenced from:
                ___pyx_pw_4borg_8compress_4ZSTD_3compress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_ZSTD_isError", referenced from:
                ___pyx_pw_4borg_8compress_4ZSTD_3compress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
                ___pyx_pw_4borg_8compress_4ZSTD_5decompress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_blake2b_final", referenced from:
                ___pyx_pw_4borg_6crypto_9low_level_11blake2b_256 in libpyembed-97bb3fdb1f46bebc.rlib(libpython.220.o)
                ___pyx_pw_4borg_6crypto_9low_level_13blake2b_128 in libpyembed-97bb3fdb1f46bebc.rlib(libpython.220.o)
               (maybe you meant: _PyBlake2_blake2b_final)
            "_LZ4_compressBound", referenced from:
                ___pyx_pw_4borg_8compress_3LZ4_3compress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_ZSTD_getErrorName", referenced from:
                ___pyx_pw_4borg_8compress_4ZSTD_3compress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
                ___pyx_pw_4borg_8compress_4ZSTD_5decompress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_LZ4_decompress_safe", referenced from:
                ___pyx_pw_4borg_8compress_3LZ4_5decompress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
            "_LZ4_compress_default", referenced from:
                ___pyx_pw_4borg_8compress_3LZ4_3compress in libpyembed-97bb3fdb1f46bebc.rlib(libpython.219.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error

error: could not compile `borg`.
```

pyoxidizer.bzl
```
def make_dist():
    return default_python_distribution()

def make_exe(dist):
    policy = dist.make_python_packaging_policy()
    policy.extension_module_filter = "all"
    policy.include_distribution_sources = True
    policy.include_distribution_resources = True
    policy.include_test = False
    policy.resources_location = "in-memory"
    policy.resources_location_fallback = "filesystem-relative:lib"
    python_config = dist.make_python_interpreter_config()
    python_config.run_mode = 'eval:from borg.archiver import main;main()'
    exe = dist.to_python_executable(
        name="borg",
        packaging_policy=policy,
        config=python_config,
    )
    exe.add_python_resources(exe.pip_install(["borgbackup"]))
    return exe

def make_embedded_resources(exe):
    return exe.to_embedded_resources()

def make_install(exe):
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files

register_target("dist", make_dist)
register_target("exe", make_exe, depends=["dist"])
register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
register_target("install", make_install, depends=["exe"], default=True)
resolve_targets()
PYOXIDIZER_VERSION = "0.8.0"
PYOXIDIZER_COMMIT = "UNKNOWN"
```

Will dig deeper in the next days. Just putting it here, in case someone has quick pointers on what to look for.
