### ISSUE TITLE
Trouble using PythonDistribution.read_package_root

### ISSUE THREAD

**Issue by pharaujo** [indygreg/PyOxidizer#223]
I was testing `read_package_root`, but I couldn't make it to work with the latest stable release (0.5.1). The starlark configuration I used was the one created using `init-config-file`, only adding the `exe.add_python_resources(dist.read_package_root` bit. I tried using both relative and absolute paths in the `path` parameter.

I created a reproducible test case:
```
pyoxidizer_test/
├── bar
│   └── __init__.py
├── foo.py
└── pyoxidizer.bzl
```

```
$ cat foo.py
print('foo')
$ cat bar/__init__.py
print('bar')
```

The only change in the generated configuration is adding the python test files:
```
$ cat pyoxidizer.bzl
def make_dist():
    return default_python_distribution()

def make_exe(dist):
    python_config = PythonInterpreterConfig()

    exe = dist.to_python_executable(
        name="foo",
        config=python_config,
        extension_module_filter='all',
        include_sources=True,
        include_resources=False,
        include_test=False,
    )

    exe.add_python_resources(dist.read_package_root(
        #path=".",
        path="/tmp/pyoxidizer_test",
        packages=["foo", "bar"],
    ))

    return exe

def make_embedded_data(exe):
    return exe.to_embedded_data()

def make_install(exe):
    files = FileManifest()
    files.add_python_resource(".", exe)

    return files

register_target("dist", make_dist)
register_target("exe", make_exe, depends=["dist"], default=True)
register_target("embedded", make_embedded_data, depends=["exe"])
register_target("install", make_install, depends=["exe"])

resolve_targets()

# END OF COMMON USER-ADJUSTED SETTINGS.
#
# Everything below this is typically managed by PyOxidizer and doesn't need
# to be updated by people.

PYOXIDIZER_VERSION = "0.5.1"
PYOXIDIZER_COMMIT = ""
```

Using a local shell, it works as expected:
```
$ python
Python 3.7.6 (default, Feb  5 2020, 15:39:04)
[Clang 11.0.0 (clang-1100.0.20.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo, bar
foo
bar
```

Running the generated REPL shows that the files apparently weren't included in the embedded environment:
```
$ pyoxidizer run
resolving 1 targets
resolving target exe
resolving target dist
resolving Python distribution Url { url: "https://github.com/indygreg/python-build-standalone/releases/download/20191025/cpython-3.7.5-macos-20191026T0535.tar.zst", sha256: "e8d0710627c017213d9c5c6496577539a5adceb56d3060e07954ce9bf59f39ae" }
Python distribution available at /private/tmp/pyoxidizer_test/./build/python_distributions/cpython-3.7.5-macos-20191026T0535.tar.zst
reading data from Python distribution...
distribution info: PythonDistributionMinimalInfo {
    flavor: "cpython",
    version: "3.7.5",
    os: "macos",
    arch: "x86_64",
    py_module_count: 1949,
}
     Created binary (application) package
(...)
writing executable to /private/tmp/pyoxidizer_test/./build/x86_64-apple-darwin/debug/exe/foo
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
>>> import bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bar'
>>>
```

Am I doing something wrong here?

**Comment by BiatuAutMiahn** [comment]
try `from foo import foo`, and `from bar import bar`?

**Comment by pharaujo** [comment]
No, that also doesn't work.

**Comment by BiatuAutMiahn** [comment]
do you have a setup.py in the foo and bar module folders?

**Comment by pharaujo** [comment]
@BiatuAutMiahn no. The test case is exactly as described in the issue: using `read_package_root`, not `setup_py_install`.

**Comment by indygreg** [comment]
I don't believe the test coverage for `read_package_root` is that good. So I'm not surprised there is a bug here. Thank you for the test case!

**Comment by indygreg** [comment]
I have found the bug responsible for this and should have a fix committed soon.
