### ISSUE TITLE
The app is not built with PySide2

### ISSUE THREAD

**Issue by Affteron** [indygreg/PyOxidizer#228]
Hi!
I ran into a problem when trying to build an application in Python with the GUI on PySide2. When i try to use the "pyoxidizer run" command, the following exception appears at the moment the application is launched:
```
PySide2/__init__.py: Unable to import shiboken2 from
Traceback (most recent call last):
  File "eln_to_excel_gui", line 1, in <module>
  File "PySide2", line 61, in <module>
  File "PySide2", line 25, in _setupQtDirectories
  File "shiboken2", line 27, in <module>
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
SystemError
error: cargo run failed

```
Can you tell me what the problem might be?

**Comment by indygreg** [comment]
There's nothing obvious standing out to me in the bug report. I'll have to try to reproduce this myself and see what's going on. I would not be surprised if this has something to do with compiled extension modules on Windows though.

**Comment by indygreg** [comment]
I should add that compatibility with pre-built extension modules is something I'm focusing on at the moment. Hopefully this "just works" in the next major PyOxidizer release.

**Comment by roesneb** [comment]
I have tried the new Release with PySide2==5.14.1
The policy i have picked is "prefer-in-memory-fallback-filesystem-relative:lib"

for resource in dist.pip_install(["my-package"]):
        if type(resource) == "PythonExtensionModule":
            exe.add_extension_module(resource)

Apart from that i have left the pyoxidizer.bzl untouched.
It builds fine and the Interpreter starts up.
Unfortunately i can't seem to import PySide2.

Am i missing something here?

PyOxidizer looks very promising i have to say though.
