### ISSUE TITLE
How do I run my application?

### ISSUE THREAD

**Issue by manfredlotz** [indygreg/PyOxidizer#246]
I tried a minimal example having a single file `hello.py`

```
#!/usr/bin/env python3

def main():
    print("Hello world!")

if __name__ == "__main__":
    main()
```

But getting a repl when runnind `pyoxidizer run` isn't what I want. I tried to use `run_module`, and `run_eval` but was not able to get my mini application to run. 

Any hints welcome.

**Comment by manfredlotz** [comment]
Perhaps I should mention that I tried `pyoxidizer run` with:

```
run_module="hello",
```
and got:

```
AttributeError: 'NoneType' object has no attribute 'loader'
error: cargo run failed
```

Then with

```
run_module="hello.main",
```
and

```
run_module="hello.__main__",
```
and  in both cases I got 

```
Traceback (most recent call last):
  File "importlib.util", line 94, in find_spec
ModuleNotFoundError: No module named 'hello'
error: cargo run failed
```

As the documentation doesn't help (or I missed a helping documentation) I have no idea what to try.

**Comment by eliotstock** [comment]
Same here. Tested on 0.7.0 and 0.6.0.

**Comment by eliotstock** [comment]
Related: #100

**Comment by mardukbp** [comment]
Assuming you are at home (`~`).

1. Create a directory for your package e.g. `hello`
2. Move `hello.py` to this directory
3. Create a work directory for PyOxidizer e.g. `hello-oxi`
4. `pyoxidizer init-config-file hello-oxi`
5. `cd hello-oxi`
6. Edit `pyoxidizer.byl` with your favorite editor
7. Around line 110 add the following lines

```
exe.add_in_memory_python_resources(dist.read_package_root(                                                                      
    path="/home/user/hello",                                                                              
    packages=["hello"],
))  
```

8. `pyoxidizer run`

When PyOxidizer finishes it will launch a Python prompt where you can enter

```
import hello
hello.main()
```

You can also add this to `pyoxidizer.bzl` in order to execute your code directly:

`run_eval=import hello; hello.main()`

**Comment by manfredlotz** [comment]
@mardukbp Thanks, this worked.

**Comment by eliotstock** [comment]
Worked for me too, thank you! This is helpful, but it still feels hacky to have to use run_eval. And in fact, run_module="hello" seems to work.

It's also not great to have to specify an absolute path to /home/user/hello. I tried with a path that's relative to the hello-oxi dir and it worked for me.

Could the docs be improved to explain the necessary directory structure?

**Comment by mardukbp** [comment]
Well, I started using PyOxidizer yesterday. So we are all learning how it works. I have not checked the docs, but if something is missing or is not clearly explained one can always submit a Pull Request :)

**Comment by stuhood** [comment]
For anyone encountering a `AttributeError: 'NoneType' object has no attribute 'loader'` error: try setting:
```
python_config = PythonInterpreterConfig(
  ..
  verbose=1,
  ..
)
```
... in your config, which will render all of the import statements leading up to the error: the last import statement is a missing package.

**Comment by gertjanklein** [comment]
The documentation definitely omits a simple "hello, world" example. Online examples are often for previous versions. I created one for 0.7 that doen't need the directory setup described above. Python:

    def main():
        print('Hello, world')
    
    if __name__ == "__main__":
        main()

`pyoxidizer.bzl`, stripped of comments:

    def make_dist():
        return default_python_distribution()
    
    def make_exe(dist):
        python_config = PythonInterpreterConfig(
             run_module='hello',
        )
        exe = dist.to_python_executable(
            name="hello",
            config=python_config,
            extension_module_filter='all',
            include_sources=False,
            include_resources=False,
            include_test=False,
        )
        exe.add_in_memory_python_resources(dist.read_package_root(
            path=".",
            packages=["hello"],
        ))
        return exe
    
    def make_embedded_resources(exe):
        return exe.to_embedded_resources()
    
    def make_install(exe):
        files = FileManifest()
        files.add_python_resource(".", exe)
        return files
    
    register_target("dist", make_dist)
    register_target("exe", make_exe, depends=["dist"], default=True)
    register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
    register_target("install", make_install, depends=["exe"])
    
    resolve_targets()
    
    PYOXIDIZER_VERSION = "0.7.0"
    PYOXIDIZER_COMMIT = "UNKNOWN"

Compile the program with `pyoxidizer build`; it should create the (on Windows) `hello.exe`.

It would be good if something like this was added to the documentation. Even better if an example was added for consoleless applications (`*.pyw`), if that is even possible; I have not been able to find out either way.

**Comment by gertjanklein** [comment]
If I add a virtual environment in sub-directory "venv" and install toml 
in that, and add

exe.add_in_memory_python_resources(dist.read_virtualenv(path="venv"))

just before the "return exe" in pyoxidizer.bzl, I can add:

import toml
print(toml.__version__)

at the top of hello.py, and get this when running:

...\hello.exe
0.10.1
Hello, world

So this appears to work.

**Comment by burner1024** [comment]
Looks like the example just dies now
```
resolving 1 targets
resolving target exe
resolving target dist
error[CM01]: Variable 'PythonInterpreterConfig' not found
 --> ./pyoxidizer.bzl:5:21
  |
5 |     python_config = PythonInterpreterConfig(
  |                     ^^^^^^^^^^^^^^^^^^^^^^^ Variable was not found


error: Variable 'PythonInterpreterConfig' not found
```
Anyone care to share an updated helloworld?

**Comment by cchaffatt** [comment]
> Perhaps I should mention that I tried `pyoxidizer run` with:
> 
> ```
> run_module="hello",
> ```
> 
> and got:
> 
> ```
> AttributeError: 'NoneType' object has no attribute 'loader'
> error: cargo run failed
> ```
> 
> Then with
> 
> ```
> run_module="hello.main",
> ```
> 
> and
> 
> ```
> run_module="hello.__main__",
> ```
> 
> and in both cases I got
> 
> ```
> Traceback (most recent call last):
>   File "importlib.util", line 94, in find_spec
> ModuleNotFoundError: No module named 'hello'
> error: cargo run failed
> ```
> 
> As the documentation doesn't help (or I missed a helping documentation) I have no idea what to try.

Hi, first of all, thanks for supporting this tool!

I am also getting an interpreter just like @manfredlotz. I have a python app that has all of the settings in the `setup.py`. Once I do a `pip install .` everything pretty much works out and I can immediately start using my python command line tool.

It would be awesome if those settings can be extracted over so we don't have to duplicate them in `pyoxidizer.bzl` (and then have to manage both).

**Comment by kambe-mikb** [comment]
This is my current test on Windows 10

**hello.py:**
```
def talk(message):
    return "Talk " + message


def main():
    print(talk("Hello World"))


if __name__ == "__main__":
    main()
```

**pyoxidizer.bzl:**
```
def make_dist():
    return default_python_distribution(python_version="3.9")


def make_policy(dist):
    policy = dist.make_python_packaging_policy()
    policy.extension_module_filter = "no-copyleft"
    policy.bytecode_optimize_level_two = True
    return policy


def make_config(dist):
    config = dist.make_python_interpreter_config()
    config.run_module = "hello"
    return config


def make_exe(dist, policy, config):
    exe = dist.to_python_executable(
        name="hello",
        packaging_policy=policy,
        config=config,
    )
    exe.windows_runtime_dlls_mode = "always"
    exe.windows_subsystem = "console"
    exe.add_python_resources(
        exe.read_package_root(path=".", packages=["hello"])
        )
    return exe


def make_embedded_resources(exe):
    return exe.to_embedded_resources()


def make_install(exe):
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files


# Dynamically enable automatic code signing.
def register_code_signers():
    if not VARS.get("ENABLE_CODE_SIGNING"):
        return


# Call our function to set up automatic code signers.
register_code_signers()


register_target("dist", make_dist)
register_target("policy", make_policy, depends=["dist"], default=True)
register_target("config", make_config, depends=["dist"], default=True)
register_target("exe", make_exe, depends=["dist", "policy", "config"], default=True)
register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
register_target("install", make_install, depends=["exe"], default=True)
resolve_targets()
```
I have tried using ``exe.make_python_module_source(name="hello", source="hello.py", is_package=False)`` for the resource definition, but it fails:
```
installing files to C:\Users\BENSON\workspace\Python Experiments\Hello\.\build\x86_64-pc-windows-msvc\debug\install
Traceback (most recent call last):
  File "runpy", line 197, in _run_module_as_main
  File "runpy", line 87, in _run_code
  File "hello", line 1, in <module>
NameError: name 'hello' is not defined
error: cargo run failed```

**Comment by manfredlotz** [comment]
I know this doesn't help you but just for the records: on my side running Linux your example works fine.

My environment contains

Python 3.10.2

rustc 1.59.0 (9d1b2106e 2022-02-23)

PyOxidizer 0.20.0
commit: 174a329a548aa5006e70a996d6bd9e567c315b0c
source: https://github.com/indygreg/PyOxidizer.git
pyembed crate location: version = "0.20.0"

**Comment by SafeEval** [comment]
Have a working config for PyOxidizer 0.22.0 that is only slightly modified from above. It includes both a local `main.py` file and a `requirements.txt` file.

Local code.

```
#!/usr/bin/env python3
# main.py
from pprint import pprint
import requests

url = "https://github.com"
print(f"[*] Requesting {url}")
response = requests.get(url)
pprint(response.text)
```

Dependencies.

```
# requirements.txt
requests==2.28.1
```

PyOxidizer configuration.

```
# pyoxidizer.bzl

def make_dist():
    return default_python_distribution(python_version="3.9")


def make_policy(dist):
    policy = dist.make_python_packaging_policy()
    policy.extension_module_filter = "no-copyleft"
    policy.bytecode_optimize_level_two = True
    return policy


def make_config(dist):
    config = dist.make_python_interpreter_config()
    config.run_module = "main"
    return config


def make_exe(dist, policy, config):
    exe = dist.to_python_executable(
        name="testapp",
        packaging_policy=policy,
        config=config,
    )
    exe.windows_runtime_dlls_mode = "always"
    exe.windows_subsystem = "console"

    # Include requirements and the root module.
    exe.add_python_resources(
        exe.pip_install(["-r", "requirements.txt"])
    )
    exe.add_python_resources(
        exe.read_package_root(path=".", packages=["main"])
    )

    return exe


def make_embedded_resources(exe):
    return exe.to_embedded_resources()


def make_install(exe):
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files


# Dynamically enable automatic code signing.
def register_code_signers():
    if not VARS.get("ENABLE_CODE_SIGNING"):
        return


# Call our function to set up automatic code signers.
register_code_signers()


register_target("dist", make_dist)
register_target("policy", make_policy, depends=["dist"], default=True)
register_target("config", make_config, depends=["dist"], default=True)
register_target("exe", make_exe, depends=["dist", "policy", "config"], default=True)
register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
register_target("install", make_install, depends=["exe"], default=True)
resolve_targets()
```

Build and run.

```
pyoxidizer build
./build/x86_64-unknown-linux-gnu/debug/install/testapp
```
