### ISSUE TITLE
cargo build fails, unable to find PyInit_oxidized_importer

### ISSUE THREAD

**Issue by dstaley** [indygreg/PyOxidizer#264]
Running `cargo build` in a fresh checkout of the repo produces the following error:

```
   [...snip...]
   Compiling pyembed v0.8.0-pre (C:\Users\Dylan\Desktop\PyOxidizer\pyembed)
   [...snip...]
   Compiling oxidized-importer v0.8.0-pre (C:\Users\Dylan\Desktop\PyOxidizer\oxidized-importer)
error[E0425]: cannot find function, tuple struct or tuple variant `PyInit_oxidized_importer` in crate `pyembed`
  --> oxidized-importer\src\lib.rs:11:14
   |
11 |     pyembed::PyInit_oxidized_importer()
   |              ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `pyembed`
   |
help: consider importing this function
   |
5  | use crate::PyInit_oxidized_importer;
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `oxidized-importer`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by indygreg** [comment]
I'm not sure what's going on here. What Rust version is this?

**Comment by dstaley** [comment]
This is on the latest nightly, `rustc 1.45.0-nightly (4bd32c980 2020-05-29)`, on Windows.

**Comment by indygreg** [comment]
I don't know what's going on.

But the `pyembed` and `oxidized-importer` crates can be finicky to build, so it likely has something to do with that. You might want to stick to `cargo build -p pyoxidizer` unless you are actively developing the other components. See https://pyoxidizer.readthedocs.io/en/latest/rust_cargo_source_checkouts.html.

**Comment by dstaley** [comment]
Ah, gotcha! Building with `cargo build -p pyoxidizer` worked.

I was under the impression that the recent commits would enable me to use libraries with native extensions like `lxml`. Does that require some sort of special configuration? While building I see:

```
Collecting lxml==4.5.1
  Using cached lxml-4.5.1-cp38-cp38-win_amd64.whl (3.5 MB)
```

But when running I get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "app", line 3, in <module>
ImportError: cannot import name 'etree' from 'lxml' (unknown location)
```

If this warrants a new issue I'd be happy to open another one!
