### ISSUE TITLE
Examples for including version.txt, j2 and non python files to executable

### ISSUE THREAD

**Issue by sankaravadivel** [indygreg/PyOxidizer#266]
I have a file named version.txt at the root folder of my python app. I need to include this in one file executable. I am not sure how do I do. that. The following link mentions additional files in the title, but the example shown here is for the inclusion of another python module. It would be great if someone can provide me some samples to include version.txt, .j2, .conf ....

https://pyoxidizer.readthedocs.io/en/v0.7.0/packaging_additional_files.html

**Comment by sankaravadivel** [comment]
I found some information [here](https://pyoxidizer.readthedocs.io/en/v0.7.0/config.html#copying-files-next-to-your-application) and modified my pyoxidizer.bzl to include version.txt like below

`def make_install(exe):
    # Create an object that represents our installed application file layout.
    files = FileManifest()
    version_mf = glob("/home/tstuser/workspace/terraform-mae/*.txt",strip_prefix="/home/tstuser/workspace/terraform-mae/")
    files.add_manifest(version_mf)
    # Add the generated executable to our install layout in the root directory.
    files.add_python_resource(".", exe)
  
    return files`

And this is my python code referencing version.txt
`    with open('./version.txt', 'r') as file:
        ver = file.read()
`
I get the following error when run my executable
`Traceback (most recent call last):
  File "mae", line 47, in <module>
  File "mae", line 39, in mae_version
FileNotFoundError: [Errno 2] No such file or directory: './version.txt'
SystemError`

I am not sure if I am understanding is right here. Any help with this is greatly appreciated. 

Thanks
Sankar

**Comment by sankaravadivel** [comment]
I was not running the build command after making this change. I assumed run command would re-build automatically. After running the build and install commands this worked. I had to change one thing though. The first parameter for the glob function should be a list and not a string.

version_mf = glob(["/home/tstuser/workspace/terraform-mae/*.txt"],strip_prefix="/home/tstuser/workspace/terraform-mae/")
