### ISSUE TITLE
importlib.metadata does not seem to work properly

### ISSUE THREAD

**Issue by vadolasi** [indygreg/PyOxidizer#304]
Whenever I try to access some method of `importlib.metadata` it returns a empty value or an error. These errors only happen when I run the executable generated by the pyoxidizer.

`metadata.entry_points()` return an empty dictionary.

`metadata.version("pip")` return `TypeError: 'list' object is not an iterator`.

During some researches I found some parts of the documentation that talk about it (https://pyoxidizer.readthedocs.io/en/stable/oxidized_importer_behavior_and_compliance.html#importlib-metadata-compatibility), but I didn't understand what it is (maybe because I am using an automatic translator)

**Comment by indygreg** [comment]
I suspect the problem is that PyOxidizer or `oxidized_importer` isn't properly recognizing files in a `.dist-info/` directory. Since the files aren't being recognized, the package metadata comes back as an error or empty. Although there could also be other bugs involved here. That `metadata.version("pip")` raising `TypeError` looks wrong.

Could you please provide steps to reproduce? Preferably a minimal `pyoxidizer.bzl` configuration file. Output from `pyoxidizer find-resources` (https://pyoxidizer.readthedocs.io/en/v0.9.0/managing_projects.html#debugging-resource-scanning-and-identification-with-find-resources) against a reproducible Python wheel or installed package would also be sufficient. I essentially need to know what Python packages are failing and which method for finding their resources you are using so I can reproduce.

**Comment by vadolasi** [comment]
The whole project is contained here:
https://github.com/vadolasi/boilee

This is the output of `pyoxidizer find-resources:
```bash
resolving Python distribution Url { url: "https://github.com/indygreg/python-build-standalone/releases/download/20201003/cpython-3.8.6-x86_64-unknown-linux-gnu-pgo-20201003T2016.tar.zst", sha256: "897bb37257a2181b64785c4688bc0b29454ddce7a634bbd491d7b59709f11531" }
downloading https://github.com/indygreg/python-build-standalone/releases/download/20201003/cpython-3.8.6-x86_64-unknown-linux-gnu-pgo-20201003T2016.tar.zst
Python distribution available at /tmp/python-distribution.mB0VGUMRvOdn/cpython-3.8.6-x86_64-unknown-linux-gnu-pgo-20201003T2016.tar.zst
reading data from Python distribution...
parsing dist/boilee-0.1.0-py3-none-any.whl as a wheel archive
File { path: boilee/__init__.py, is_executable: false }
PythonModuleSource { name: boilee, is_package: true, is_stdlib: false, is_test: false }
File { path: boilee/__main__.py, is_executable: false }
PythonModuleSource { name: boilee.__main__, is_package: false, is_stdlib: false, is_test: false }
File { path: boilee/database.py, is_executable: false }
PythonModuleSource { name: boilee.database, is_package: false, is_stdlib: false, is_test: false }
File { path: boilee/scripts/__init__.py, is_executable: false }
PythonModuleSource { name: boilee.scripts, is_package: true, is_stdlib: false, is_test: false }
File { path: boilee/scripts/boilee.py, is_executable: false }
PythonModuleSource { name: boilee.scripts.boilee, is_package: false, is_stdlib: false, is_test: false }
File { path: boilee-0.1.0.dist-info/LICENSE, is_executable: false }
PythonPackageDistributionResource { package: boilee, version: 0.1.0, name: LICENSE }
File { path: boilee-0.1.0.dist-info/METADATA, is_executable: false }
PythonPackageDistributionResource { package: boilee, version: 0.1.0, name: METADATA }
File { path: boilee-0.1.0.dist-info/RECORD, is_executable: false }
PythonPackageDistributionResource { package: boilee, version: 0.1.0, name: RECORD }
File { path: boilee-0.1.0.dist-info/WHEEL, is_executable: false }
PythonPackageDistributionResource { package: boilee, version: 0.1.0, name: WHEEL }
File { path: boilee-0.1.0.dist-info/entry_points.txt, is_executable: false }
PythonPackageDistributionResource { package: boilee, version: 0.1.0, name: entry_points.txt }
File { path: boilee-0.1.0.dist-info/top_level.txt, is_executable: false }
PythonPackageDistributionResource { package: boilee, version: 0.1.0, name: top_level.txt }
```

**Comment by mlech-reef** [comment]
Hi! Any progress on that. I have the same problem

```
>>> from importlib import metadata
>>> metadata.version('b2sdk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "importlib.metadata", line 531, in version
  File "importlib.metadata", line 504, in distribution
  File "importlib.metadata", line 173, in from_name
TypeError: 'list' object is not an iterator
```

Is it because `from_name` is not defined according to https://pyoxidizer.readthedocs.io/en/latest/oxidized_importer_behavior_and_compliance.html#importlib-metadata-compatibility ?

**Comment by indygreg** [comment]
The error in the previous comment is almost certainly due to `from_name` not being implemented.

The list of resources from @vadolasi's last comment also looks correct. So my guess is all the errors reported in this issue are due to various APIs either not being implemented at all or being implemented incorrectly.

This seems like an area ripe for improvement. And I've been hacking on the `pyembed` crate a lot recently. So this feels like something I can improve in the next few days...

**Comment by indygreg** [comment]
@wkschwartz heads up: I might be changing code in the loader that could introduce rebase conflicts with your in-flight work. Although most of your code is new code, so resolving the conflicts should be trivial.

**Comment by wkschwartz** [comment]
I'll hold off working on your review until early this coming week so you can finish your `importlib.metadata`-related changes first.

**Comment by indygreg** [comment]
I also discovered that code in Python's standard library is expecting `find_distributions()` to return an iterator instead of an iterable object. This apparently changed in the recent months as 3.8.7 expects an iterator but 3.9.2 casts the result to a `list()` first, accepting both a list and an iterator.

The return value does not appear to be defined by Python's documentation. I'm changing PyOxidizer to return an iterator so it is more compatible.

**Comment by indygreg** [comment]
I just pushed a handful of commits for improving the implementation of the `importlib.metadata` interface. A number of new tests were also added.

I suspect the change with the biggest impact was the aforementioned change to return an iterator of distributions instead of a list. It looks like a lot of call sites in `importlib.metadata` were assuming an iterator would be returned.

Please test code in the `main` branch and let me know if you find any more incompatibilities. The only one that might not be fixed is `metadata.entry_points()` returning an empty dictionary. But `entry_points()` _should_ be implemented. So I'm hopeful that other changes caused it to start working.
