### ISSUE TITLE
Starlark panic when trying to build hg

### ISSUE THREAD

**Issue by durin42** [indygreg/PyOxidizer#314]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BorrowedMut', /Users/augie/.cargo/registry/src/github.com-1ecc6299db9ec823/starlark-0.3.1/src/values/mod.rs:199:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::unwrap
             at /Users/augie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973
   4: starlark::values::Value::value_holder
             at /Users/augie/.cargo/registry/src/github.com-1ecc6299db9ec823/starlark-0.3.1/src/values/mod.rs:199
   5: starlark::values::Value::downcast_ref
             at /Users/augie/.cargo/registry/src/github.com-1ecc6299db9ec823/starlark-0.3.1/src/values/mod.rs:1330
   6: pyoxidizer::starlark::env::PyOxidizerEnvironmentContext::build_path
             at /Users/augie/Programming/pyoxidizer/pyoxidizer/src/starlark/env.rs:103
   7: pyoxidizer::starlark::eval::EvaluationContext::build_resolved_target
             at /Users/augie/Programming/pyoxidizer/pyoxidizer/src/starlark/eval.rs:172
   8: pyoxidizer::projectmgmt::build
             at /Users/augie/Programming/pyoxidizer/pyoxidizer/src/projectmgmt.rs:125
   9: pyoxidizer::cli::run_cli
             at /Users/augie/Programming/pyoxidizer/pyoxidizer/src/cli.rs:361
  10: pyoxidizer::main
             at /Users/augie/Programming/pyoxidizer/pyoxidizer/src/main.rs:44
  11: core::ops::function::FnOnce::call_once
             at /Users/augie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I had to patch pyoxidizer.bzl for API changes:
```
# HG changeset patch
# User Augie Fackler <augie@google.com>
# Date 1604438733 18000
#      Tue Nov 03 16:25:33 2020 -0500
# Node ID 5c1c2d746f9bc4eef6ace56eb2db5f254b282fad
# Parent  58e7ee23ddbd2e90ce4a256a2f2d182c03d0b73e
DO NOT SUBMIT: more pyoxidizer hackery

diff --git a/rust/hgcli/pyoxidizer.bzl b/rust/hgcli/pyoxidizer.bzl
--- a/rust/hgcli/pyoxidizer.bzl
+++ b/rust/hgcli/pyoxidizer.bzl
@@ -14,6 +14,8 @@ def make_distribution_windows():
     return default_python_distribution(flavor = "standalone_dynamic")
 
 def resource_callback(policy, resource):
+    resource.add_location = "in-memory"
+    return
     # We use a custom resource routing policy to influence where things are loaded
     # from.
     #
@@ -40,12 +42,11 @@ def make_exe(dist):
     # extensions.
     packaging_policy.extension_module_filter = "all"
     packaging_policy.resources_location = "in-memory"
-    packaging_policy.resources_location_fallback = "filesystem-relative:lib"
     packaging_policy.register_resource_callback(resource_callback)
 
     config = dist.make_python_interpreter_config()
     config.raw_allocator = "system"
-    config.run_mode = "eval:%s" % RUN_CODE
+    config.run_command = RUN_CODE
     # We want to let the user load extensions from the file system
     config.filesystem_importer = True
     # We need this to make resourceutil happy, since it looks for sys.frozen.
```

**Comment by ryancinsight** [comment]
I can second this issue on windows 10 with pyoxidizer-0.10pre but not having this issue on pyoxidizer-0.9. Was working originally after tcl change you made so must be after a more recent changes of 0.10-pre in my situation. 

However, error on 'Result::unwrap()`

**Comment by indygreg** [comment]
I think I pushed a fix. But I didn't confirm via a reproducing test case first. If you could please verify things are working on the `main` branch, it would be appreciated!

**Comment by durin42** [comment]
Confirmed fixed, many thanks!
