### ISSUE TITLE
ImportError: libffi-806b1a9d.so.6.0.4: cannot open shared object file

### ISSUE THREAD

**Issue by pschmitt** [indygreg/PyOxidizer#316]
Just discovered this great project and I been trying to build [pkp](https://github.com/pschmitt/pkp) which relies on [pykeepass](https://github.com/libkeepass/pykeepass).
The binary builds fine with `pyoxidizer build` but at runtime I get the following:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pkp", line 12, in <module>
  File "pykeepass", line 2, in <module>
  File "pykeepass.pykeepass", line 23, in <module>
  File "pykeepass.kdbx_parsing", line 1, in <module>
  File "pykeepass.kdbx_parsing.kdbx", line 4, in <module>
  File "pykeepass.kdbx_parsing.kdbx4", line 6, in <module>
  File "argon2", line 5, in <module>
  File "argon2.low_level", line 17, in <module>
ImportError: libffi-806b1a9d.so.6.0.4: cannot open shared object file: No such file or directory
```
I'm just starting so I may have overlooked something obvious in the docs. Thanks for your work on this!

<details>
  <summary>pyoxidizer.bzl</summary>
  
```
def make_dist():
    return default_python_distribution()
def make_exe(dist):
    policy = dist.make_python_packaging_policy()
    policy.resources_location = "filesystem-relative:lib"
    python_config = dist.make_python_interpreter_config()
    python_config.run_mode = "eval:from pkp import cli_main; cli_main()"
    exe = dist.to_python_executable(
        name="pkp-oxy",
        packaging_policy=policy,
        config=python_config,
    )
    exe.add_python_resources(exe.pip_install(["pkp==0.6.3"]))
    return exe
def make_embedded_resources(exe):
    return exe.to_embedded_resources()
def make_install(exe):
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files
register_target("dist", make_dist)
register_target("exe", make_exe, depends=["dist"])
register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
register_target("install", make_install, depends=["exe"], default=True)
resolve_targets()
PYOXIDIZER_VERSION = "0.9.0"
PYOXIDIZER_COMMIT = "UNKNOWN"
```
</details>

**Comment by massyah** [comment]
Hi @pschmitt,
Had the same error when trying to run a binary including the `cryptography` module. 

Did you mange to solve the issue ?

**Comment by massyah** [comment]
could be related to #26

**Comment by pajowu** [comment]
We had a simlar problem with including libraries and solved it by switching to file based imports and force-including the native dependencies: https://github.com/audapolis/audapolis/commit/ddc5b53d08aaa6d7f5fa86322b385143f7f55c92

**Comment by ml1nk** [comment]
Comparable issue with "vsphere-automation-sdk-python". 
@pajowu I tried your changes to bzl but with no avail.

~~~
File "vmware.vapi.vsphere.client", line 13, in <module>
File "vmware.vapi.lib.connect", line 11, in <module>
File "vmware.vapi.lib.ssl", line 8, in <module>
File "OpenSSL", line 8, in <module>
File "OpenSSL.crypto", line 17, in <module>
File "OpenSSL._util", line 6, in <module>
File "cryptography.hazmat.bindings.openssl.binding", line 14, in <module>
ImportError: libffi-9c61262e.so.8.1.0: cannot open shared object file: No such file or directory
