### ISSUE TITLE
Failed to build on Ubuntu 18.04 at pyembed v0.1.0

### ISSUE THREAD

**Issue by helioloureiro** [indygreg/PyOxidizer#32]
Hi,

I just cloned the repo and run "cargo build":

**Comment by helioloureiro** [comment]
Further info:

helio@xps13ubuntu:PyOxidizer$ env RUST_BACKTRACE=1 cargo build
   Compiling pyembed v0.1.0 (/home/ehellou/DEVEL/PyOxidizer/pyembed)
error: failed to run custom build command for `pyembed v0.1.0 (/home/ehellou/DEVEL/PyOxidizer/pyembed)`
process didn't exit successfully: `/home/ehellou/DEVEL/PyOxidizer/target/debug/build/pyembed-cdba5daab28bc600/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-env-changed=PYOXIDIZER_CONFIG

--- stderr
thread 'main' panicked at 'Could not find PyOxidizer config file', pyoxidizer/src/pyrepackager/repackage.rs:2640:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /usr/src/rustc-1.32.0/src/libstd/panicking.rs:425
   6: pyoxidizerlib::pyrepackager::repackage::run_from_build
             at pyoxidizer/src/pyrepackager/repackage.rs:2640
   7: build_script_build::main
             at pyembed/build.rs:41
   8: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.32.0/src/libstd/rt.rs:74
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start_internal
  12: std::rt::lang_start
             at /usr/src/rustc-1.32.0/src/libstd/rt.rs:74
  13: main
  14: __libc_start_main
  15: _start

**Comment by indygreg** [comment]
Ahh - the repo doesn't `cargo build` by default because the Rust workspace contains a half-working demo application (`pyapp`) that requires a `pyoxidizer.toml` file to exist.

This experience is not great and we should fix the default experience so it is better.

If you `cargo build --bin pyoxidizer`, it will do what you want.
