### ISSUE TITLE
packaging: SyntaxError while byte compiling causes panic

### ISSUE THREAD

**Issue by wkschwartz** [indygreg/PyOxidizer#334]
<details>
<summary>Version</summary>

```console
$ pyoxidizer --version
PyOxidizer 0.11.0-pre
commit: 6875c5fd1f5c6df3c1a24734868393a1ae19cb57
```

</details>

Paste the following into `pyoxidizer.bzl` in an otherwise empty directory.

```bzl
def make():
    dist = default_python_distribution()
    exe = dist.to_python_executable(
        name="pyapp",
        packaging_policy=dist.make_python_packaging_policy(),
        config=dist.make_python_interpreter_config(),
    )
    exe.add_python_resource(exe.make_python_module_source(
        name="foo",
        source="you're looking at a SyntaxError",
        is_package=False))
    return exe
register_target("exe", make, default=True)
resolve_targets()
```

Similar to #147, this causes a "panicked while panicking" crash.

<details>
<summary>Backtrace</summary>

```console
$ RUST_BACKTRACE=1 pyoxidizer build   # output snipped
warning: zipimport contains __file__
__file__ was encountered in some embedded modules
PyOxidizer does not set __file__ and this may create problems at run-time
See https://github.com/indygreg/PyOxidizer/issues/69 for more
Traceback (most recent call last):
  File "/var/folders/bj/86dpvqnn57d552p_grqxjh9h0000gn/T/bytecode-compiler.mnKbFIVvEgQK/bytecodecompiler.py", line 72, in <module>
    code = compile(source, name, "exec", optimize=optimize_level)
  File "foo", line 1
    you're looking at a SyntaxError
                                  ^
SyntaxError: EOL while scanning string literal
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', python-packaging/src/bytecode.rs:140:49
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_none_failed
   3: <python_packaging::bytecode::BytecodeCompiler as python_packaging::bytecode::PythonBytecodeCompiler>::compile
   4: python_packaging::resource_collection::PrePackagedResource::to_resource
   5: python_packaging::resource_collection::PythonResourceCollector::compile_resources
   6: <pyoxidizer::py_packaging::standalone_builder::StandalonePythonExecutableBuilder as pyoxidizer::py_packaging::binary::PythonBinaryBuilder>::to_embedded_python_context
   7: pyoxidizer::project_building::build_python_executable
   8: pyoxidizer::starlark::python_executable::build
   9: <T as starlark::values::TypedValueDyn>::call_dyn
  10: starlark::values::Value::call
  11: pyoxidizer::starlark::eval::EvaluationContext::build_resolved_target
  12: pyoxidizer::projectmgmt::build
  13: pyoxidizer::cli::run_cli
  14: pyoxidizer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'write failed: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', python-packaging/src/bytecode.rs:152:36
stack backtrace:
   0:        0x10ce29874 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
   1:        0x10ce50ce0 - core::fmt::write::h94ae1e793baa7a00
   2:        0x10ce2173b - std::io::Write::write_fmt::h5c716758fdc3057f
   3:        0x10ce2d405 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
   4:        0x10ce2d147 - std::panicking::default_hook::heae8b62897b351dc
   5:        0x10ce2d9a5 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
   6:        0x10ce2d53b - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
   7:        0x10ce29ce8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
   8:        0x10ce2d4fa - _rust_begin_unwind
   9:        0x10ce7b09f - core::panicking::panic_fmt::hcdc9362d34d55302
  10:        0x10ce7afa5 - core::option::expect_none_failed::hef0458611b13747b
  11:        0x10caa9a76 - <python_packaging::bytecode::BytecodeCompiler as core::ops::drop::Drop>::drop::h73c81d104aeb0b51
  12:        0x10c646d8f - core::ptr::drop_in_place::h76880aa30a2ad8c6
  13:        0x10c65cb67 - <pyoxidizer::py_packaging::standalone_builder::StandalonePythonExecutableBuilder as pyoxidizer::py_packaging::binary::PythonBinaryBuilder>::to_embedded_python_context::hb6acdfb053e46ca1
  14:        0x10c637f55 - pyoxidizer::project_building::build_python_executable::hf1fa216c6d4ec926
  15:        0x10c615709 - pyoxidizer::starlark::python_executable::build::h0cd355fa0c72ac90
  16:        0x10ccb9284 - <T as starlark::values::TypedValueDyn>::call_dyn::hdd405a9fed732f79
  17:        0x10cd22df5 - starlark::values::Value::call::hfea6101965c23f4e
  18:        0x10c60fb1e - pyoxidizer::starlark::eval::EvaluationContext::build_resolved_target::h4929c84c0fcbfe2f
  19:        0x10c5546c6 - pyoxidizer::projectmgmt::build::h32222efedcf0b0ef
  20:        0x10c651a13 - pyoxidizer::cli::run_cli::hd75638e0db2ef5b0
  21:        0x10c580c7e - pyoxidizer::main::hd65468e16a69de77
  22:        0x10c5fe94a - std::sys_common::backtrace::__rust_begin_short_backtrace::hc663537e954d816e
  23:        0x10c5fe98c - std::rt::lang_start::{{closure}}::hface0ac8325250e1
  24:        0x10ce2dd40 - std::rt::lang_start_internal::hd0c760d47f593c0a
  25:        0x10c5812b9 - _main
thread panicked while panicking. aborting.
[1]    29506 illegal hardware instruction  RUST_BACKTRACE=1 pyoxidizer build
```

</details>

Coming to a hard stop and refusing to produce the executable makes sense, but a better error message would be nice. I'm guessing the place to put it would be either `pyoxidizer::py_packaging::standalone_builder::StandalonePythonExecutableBuilder::to_embedded_python_context` or `python_packaging::bytecode::BytecodeCompiler::drop`.

**Comment by indygreg** [comment]
Yikes. I'm pretty surprised this results in a panic! This looks to be an issue with how we handle output from the Python subprocess.

Thank you for filing this!

**Comment by indygreg** [comment]
I'm unable to reproduce this against the `main` branch. That's probably because f71c51214caf101465bf6000cd347d9947e4ea93 added error handling as part of investigating an unrelated bug. Regardless, I added a test case to ensure this doesn't silently regress.

Thank you for reporting this bug.
