### ISSUE TITLE
Build fails in Centos 7 due to jemalloc error

### ISSUE THREAD

**Issue by harelba** [indygreg/PyOxidizer#469]
Hi, running `pyoxidizer build --release` in a standard docker container `centos:7` for the project [q](https://github.com/harelba/q).

The build fails with the following error:
```
thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.2/build.rs:389:19
```

When compiling on centos:8 everything works fine (working on centos8, failing on glibc version for centos7).

Would be really glad to get any insight you might have.

Attached `--verbose` log file.

Also, running with `RUST_BACKTRACE=full` shows the following trace:
```
  thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.2/build.rs:389:19
  stack backtrace:
     0:     0x562647cb9c00 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x562647cb9c00 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x562647cb9c00 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x562647cb9c00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x562647cd9dfc - core::fmt::write::h306731c068f7162c
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
     5:     0x562647cb68f5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
     6:     0x562647cbc21b - std::sys_common::backtrace::_print::h5abaa2601a852287
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x562647cbc21b - std::sys_common::backtrace::print::h8d81445442bb638f
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x562647cbc21b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
     9:     0x562647cbbcf1 - std::panicking::default_hook::hbea8e3ccf2ba8901
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
    10:     0x562647cbc8e4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
    11:     0x562647cbc3c7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
    12:     0x562647cba0fc - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x562647cbc329 - rust_begin_unwind
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
    14:     0x562647c3e4ab - std::panicking::begin_panic_fmt::h5479575e112541f8
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
    15:     0x562647c44ca4 - build_script_build::run::he58de59919e9495c
    16:     0x562647c435f4 - build_script_build::main::hac32f579a21b86f3
    17:     0x562647c49a43 - core::ops::function::FnOnce::call_once::he16954a34d4be86f
    18:     0x562647c50fd9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3d2f8e162b36fad0
    19:     0x562647c4ecd9 - std::rt::lang_start::{{closure}}::hc97222691d52e5f6
    20:     0x562647cbcde9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
    21:     0x562647cbcde9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
    22:     0x562647cbcde9 - std::panicking::try::hb5d9603af3abbe3a
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
    23:     0x562647cbcde9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
    24:     0x562647cbcde9 - std::rt::lang_start_internal::h22ac7383c516f93e
                                 at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
    25:     0x562647c4ecc1 - std::rt::lang_start::h2a7ad7b2f8266150
    26:     0x562647c45253 - main
    27:     0x7fa07e3e3555 - __libc_start_main
    28:     0x562647c3f3b1 - <unknown>
    29:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: reading cargo output
    3: command ["/root/.cache/pyoxidizer/rust/1.54.0-x86_64-unknown-linux-gnu/bin/cargo", "build", "--target", "x86_64-unknown-linux-gnu", "--target-dir", "/tmp/pyoxidizer0XgANl/build/target", "--bin", "q", "--locked", "--release", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101
```

**Comment by l00ptr** [comment]
I ran into this issue on RockyLinux8. and it was mainly because make & autoconf were missing. @dae thx for the hint :)

**Comment by lorengordon** [comment]
Followed the error message here, also resolved by installing make and autoconf. Thanks!
