### ISSUE TITLE
Unable to access metadata for a package with capitals in its name

### ISSUE THREAD

**Issue by cjmayo** [indygreg/PyOxidizer#488]
```sh
$ pyoxidizer run
...
Traceback (most recent call last):
  File "runpy", line 197, in _run_module_as_main
  File "runpy", line 87, in _run_code
  File "onetwo.__main__", line 3, in <module>
  File "importlib.metadata", line 541, in metadata
  File "importlib.metadata", line 187, in from_name
importlib.metadata.PackageNotFoundError: OneTwo
error: cargo run failed
```

```
pyoxidizer.bzl
setup.py
onetwo/
    __main__.py
```

setup.py:
```py
#!/usr/bin/python3

from setuptools import setup

setup(
	name="OneTwo",
	packages=["onetwo"],
)

```

`__main__.py`:
```py
from importlib.metadata import metadata

print(metadata("OneTwo")["Name"])
```

pyoxidizer.bzl:
```py
def make_exe():
    dist = default_python_distribution()
    python_config = dist.make_python_interpreter_config()
    python_config.run_module = "onetwo"
    exe = dist.to_python_executable(
        name="onetwo",
        config=python_config,
    )
    exe.add_python_resources(exe.pip_install([CWD]))
    return exe

register_target("exe", make_exe)
resolve_targets()
```

Runs if both OneTwo are replaced with onetwo.

```
$ pyoxidizer --version
PyOxidizer 0.18.0
commit: 0e47cdb07bd8fd0913925f08b03c393d86871a1d
source: https://github.com/indygreg/PyOxidizer.git
pyembed crate location: version = "0.18.0"
```

**Comment by franzhaas** [comment]
I may be wrong, but i think the parameter to metadata is the package, specified by the packages parameter to setup, and name is the name of the distribution as specified by the name parameter to the setup call.

**Comment by indygreg** [comment]
Thanks for this report. Names in `importlib.metadata` are normalized and it looks like the Rust implementation of `importlib.metadata` APIs isn't performing this normalization correctly. This is a legitimate bug.
