### ISSUE TITLE
numpy in sinlge file executable

### ISSUE THREAD

**Issue by franzhaas** [indygreg/PyOxidizer#489]
Hi,

i managed to modify numpy to work in a sinlge file exectuble by removing __file__ usage, droping blas suport and checking for __file__existance.

I did not manage to get the numpy.random part of numpy to work. When loading numpy.random, and single steppinig trought the import  process, i get 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy.random", line 180, in <module>
  File "<frozen importlib._bootstrap>", line 211, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 110, in acquire

when letting it run, i get a crash.

It apears to break in the locking code, and this code behaves differently depending on execution speed. so far it makes sense.

However, it is hard for me to really understand whats going on, i can not access the source of importlib._bootstrap using inspect, and i am suprised that other pyd files from numpy do load fine.

Looking on potentially the right sourcecode by file name and function name and google, it apears as if the same thread identifier gets used twice to delete an entry of an a dictionary.

This is odd.

any hints?

**Comment by franzhaas** [comment]
Note.:
the code i assumed to be the one throwing the exception is.:
https://github.com/python/cpython/blob/main/Lib/importlib/_bootstrap.py

the fork of numpy that mostly runs on single file executable (+the view dlls)
https://github.com/franzhaas/numpy

**Comment by franzhaas** [comment]
this can be closed, and the simpler #490 can be used instead
