### ISSUE TITLE
Is there a way to include Java VM into the bundle?

### ISSUE THREAD

**Issue by tropxy** [indygreg/PyOxidizer#503]
Hey,

My app builds with Pyoxidizer I and I was able to start it, but the execution fails with the following:
```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "iso15118.secc.start_secc", line 5, in <module>
  File "iso15118.secc.comm_session_handler", line 25, in <module>
  File "iso15118.secc.transport.tcp_server", line 8, in <module>
  File "iso15118.shared.security", line 43, in <module>
  File "iso15118.shared.exi_codec", line 39, in <module>
  File "iso15118.shared.exificient_wrapper", line 22, in __init__
  File "py4j.java_gateway", line 2159, in launch_gateway
  File "py4j.java_gateway", line 297, in launch_gateway
py4j.protocol.Py4JError: Could not find py4j jar at
```
That last debug line is the execution of the following line of code, in the py4j lib:
https://github.com/bartdag/py4j/blob/fd1fb670f06c88d467eacf463f0aed8f55ebde53/py4j-python/src/py4j/java_gateway.py#L297

I think the problem is because the executable does not contain or cant find the Java VM, which is installed in my host, but is not included in the bundle. Is there a way to include or link the Java VM to the bundle, so that this error is no longer raised?

Thank you!

**Comment by tropxy** [comment]
I see that pyoxidizer does not have support for arm archs. I find this surprising as rust can cross compile to arm and so can the bindings for python using PyO3. With PyO3 one can tell maturin to use a specific python interpreter (compiled to the target arch) and to cross build to arm....I wonder why is that not straightforward with pyoxidizer.

**Comment by indygreg** [comment]
It sounds like there are potentially 2 problems: embedding a JVM in a binary and ARM support.

Lack of ARM support is because early versions of PyOxidizer weren't able to support cross-compiling very well. That is now better with the switch to PyO3. So lack of ARM support now is due to not putting in the effort to implement. It is on my short list for new features in the next release. There's little excuse for not having it implemented now.

As for embedding a JVM, I doubt you'll get that to work from a single file binary. It is best to use a classic distribution format (e.g. .py[c] files) for shipping resource files. As whatever py4j is doing is almost certainly not compatible with PyOxidizer's mode for loading resources from memory.
