### ISSUE TITLE
panic while signing a release build of a flutter ios app

### ISSUE THREAD

**Issue by dvc94ch** [indygreg/PyOxidizer#544]
thread 'main' panicked at 'slice index starts at 3031040 but ends at 0': /Users/dvc/.cargo/git/checkouts/pyoxidizer-04b02466db45c615/89d4253/apple-codesign/src/macho_signing.rs:194

reaching github upload limits, so can't upload the appbundle that doesn't sign

```
thread 'main' panicked at 'slice index starts at 3031040 but ends at 0', library/core/src/slice/index.rs:91:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9c06e1ba47e1077725a950e0b5d1870a89c8b536/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9c06e1ba47e1077725a950e0b5d1870a89c8b536/library/core/src/panicking.rs:143:14
   2: core::slice::index::slice_index_order_fail_rt
             at /rustc/9c06e1ba47e1077725a950e0b5d1870a89c8b536/library/core/src/slice/index.rs:91:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/9c06e1ba47e1077725a950e0b5d1870a89c8b536/library/core/src/ops/function.rs:227:5
   4: core::intrinsics::const_eval_select
             at /rustc/9c06e1ba47e1077725a950e0b5d1870a89c8b536/library/core/src/intrinsics.rs:2366:5
   5: core::slice::index::slice_index_order_fail
             at /rustc/9c06e1ba47e1077725a950e0b5d1870a89c8b536/library/core/src/slice/index.rs:86:14
   6: rcodesign::macho_signing::create_macho_with_signature
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: core::iter::adapters::try_process
  10: rcodesign::macho_signing::MachOSigner::write_signed_binary
  11: rcodesign::bundle_signing::SingleBundleSigner::write_signed_bundle
  12: rcodesign::bundle_signing::BundleSigner::write_signed_bundle
  13: rcodesign::signing::UnifiedSigner::sign_path
  14: rcodesign::command_sign
  15: rcodesign::main_impl
  16: rcodesign::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by indygreg** [comment]
This should be debuggable by pasting the output of `rcodesign extract --data macho-segments path/to/macho-binary`

**Comment by dvc94ch** [comment]
not convinced yet that the binary isn't failing to sign because it's somehow corrupt.

```
rcodesign extract --data macho-segments helloworld.app/main
segments count: 6
segment #0; __PAGEZERO; offsets=0x0-0x0; vm/file size 4294967296/0; section count 0
segment #1; __TEXT; offsets=0x0-0xf4000; vm/file size 999424/999424; section count 10
segment #1; section #0: __text; segment offsets=0x4000-0xc8524 size 804132
segment #1; section #1: __stubs; segment offsets=0xc8524-0xc8cb0 size 1932
segment #1; section #2: __stub_helper; segment offsets=0xc8cb0-0xc9454 size 1956
segment #1; section #3: __cstring; segment offsets=0xc9454-0xc96a4 size 592
segment #1; section #4: __gcc_except_tab; segment offsets=0xc96a4-0xcc6a8 size 12292
segment #1; section #5: __const; segment offsets=0xcc6b0-0xeed60 size 140976
segment #1; section #6: __literal4; segment offsets=0xeed60-0xef070 size 784
segment #1; section #7: __literal8; segment offsets=0xef070-0xef538 size 1224
segment #1; section #8: __literal16; segment offsets=0xef540-0xeff10 size 2512
segment #1; section #9: __unwind_info; segment offsets=0xeff10-0xf2b90 size 11392
segment #2; __DATA_CONST; offsets=0xf4000-0xf8000; vm/file size 16384/16384; section count 1
segment #2; section #0: __got; segment offsets=0xf4000-0xf4020 size 32
segment #3; __DATA; offsets=0xf8000-0x104000; vm/file size 49152/49152; section count 12
segment #3; section #0: __la_symbol_ptr; segment offsets=0xf8000-0xf8508 size 1288
segment #3; section #1: __const; segment offsets=0xf8508-0x102738 size 41520
segment #3; section #2: __data; segment offsets=0x102738-0x1029f8 size 704
segment #3; section #3: __objc_classrefs; segment offsets=0x1029f8-0x102a10 size 24
segment #3; section #4: __objc_selrefs; segment offsets=0x102a10-0x102a50 size 64
segment #3; section #5: __objc_const; segment offsets=0x102a50-0x102b00 size 176
segment #3; section #6: __objc_data; segment offsets=0x102b00-0x102b50 size 80
segment #3; section #7: __cfstring; segment offsets=0x102b50-0x102b70 size 32
segment #3; section #8: __objc_classlist; segment offsets=0x102b70-0x102b78 size 8
segment #3; section #9: __objc_imageinfo; segment offsets=0x102b78-0x102b80 size 8
segment #3; section #10: __common; segment offsets=0x0-0x31 size 49
segment #3; section #11: __bss; segment offsets=0x0-0x170 size 368
segment #4; __LLVM; offsets=0x104000-0xabc000; vm/file size 10190848/10190848; section count 3
segment #4; section #0: __bitcode; segment offsets=0x104000-0xaaddf0 size 10132976
segment #4; section #1: __cmdline; segment offsets=0xaaddf0-0xab8a67 size 44151
segment #4; section #2: __asm; segment offsets=0xab8a67-0xab8acb size 100
segment #5; __LINKEDIT; offsets=0xabc000-0xc02188; vm/file size 1335688/1335688; section count 0
```

**Comment by indygreg** [comment]
The source file is fine. All the segments look normal and aren't overlapping.

If this is the source file for the given assertion message, the only thing I can think of is that our Mach-O modification logic is corrupting the Mach-O segment records somehow. The assertion messages seems to indicate that `segment.filesize == 0`.

You should start printing out the raw segment structures in the failing code and where we modify the segment structs a few lines above. This bug is almost certainly in the function throwing the assertion and is due to how we calculate segment sizes/offsets.
