### ISSUE TITLE
import raven fails

### ISSUE THREAD

**Issue by gjcarneiro** [indygreg/PyOxidizer#63]
```
yacron-app packaged into /home/gjc/projects/yacron-app/build/apps/yacron-app/debug
Traceback (most recent call last):
  File "yacron.__main__", line 8, in <module>
  File "yacron.cron", line 10, in <module>
  File "yacron.job", line 11, in <module>
  File "raven", line 44, in <module>
  File "raven", line 30, in get_revision
NameError: name '__file__' is not defined
SystemError
error: cargo run failed
```

**Comment by TxBillbr** [comment]
I was able to use the work-around in the documentation for the keyring package with success in dealing with __file__ in 3rd-party packages. You might try that as a method. It does mean that you end up with a lib directory carry along with the .exe in windows. (I haven't tried it in Mac or Linux, but would think that you get a shared lib there.)

**Comment by gjcarneiro** [comment]
Ah, I missed the doc section about this.  Maybe I should open a bug in raven, instead.

**Comment by indygreg** [comment]
See also #69. I encourage people to create issues against 3rd party projects when those projects require `__file__`. If someone files an issue against Raven, please link to #69, as that issue contains all the details.

**Comment by jayvdb** [comment]
fwiw, [`raven`](https://pypi.org/project/raven/ ) is deprecated and replaced with [`sentry`](https://pypi.org/project/sentry/), and it looks like https://github.com/getsentry/sentry-python still uses `__file__` but it degrades gracefully if it doesnt exist.
