### ISSUE TITLE
unknown option --multiprocessing-fork

### ISSUE THREAD

**Issue by LyronFoster** [indygreg/PyOxidizer#633]
unknown option --multiprocessing-fork
Try `python -h' for more information.
error instantiating embedded Python interpreter: during initializing Python core: could not format PyStatus

What usually causes this error? The same build and configuration works fine on Linux and Mac.

**Comment by diogofriggo** [comment]
In my case I had this one set:
python_config.config_profile = "python"
which makes the .exe generated by PyOxidizer to not recognize the --multiprocessing-fork flag
that fixes this issue but reveals another one though:
Traceback (most recent call last):
  File "multiprocessing.spawn", line 107, in spawn_main
  File "multiprocessing.reduction", line 79, in duplicate
TypeError: DuplicateHandle() argument 2 must be int, not dict
which I don't know how to solve
