### ISSUE TITLE
Unable to Use libopenSSL in compiled application

### ISSUE THREAD

**Issue by magicaldave** [indygreg/PyOxidizer#757]
Hi! 

I'm very excited to transition my python app from nuitka to a rust-first binary with signing etc. I've got *almost* everything working. Here's my `pyoxidizer.bzl` file: (as a `.txt`, because github)

[pyoxidizer.txt](https://github.com/user-attachments/files/18050567/pyoxidizer.txt)

The goal of this particular project is simple: Shut up, be a binary, load the python code that does the real work.
This *almost* works perfectly, but I can't quite tell why `pyoxidizer` is missing the libopenssl library `curldl` is after, here. 
Runtime logs follow:
```
18:51:37 sk3shun-8@UNDEAD-ASYLUM GitHub/umomwd ? 1 % ./src-rs/build/x86_64-unknown-linux-gnu/debug/install/umo-rs info
Traceback (most recent call last):
  File "runpy", line 196, in _run_module_as_main
  File "runpy", line 86, in _run_code
  File "umo", line 554, in <module>
  File "umo", line 206, in <lambda>
  File "umo", line 179, in call_subcmd
  File "subcmds", line 35, in <module>
  File "handlers", line 27, in <module>
  File "curldl", line 3, in <module>
  File "curldl.curldl", line 12, in <module>
ImportError: libssl-52849bc7.so.1.1.1k: cannot open shared object file: No such file or directory
```

Just to be clear, I've got `libssl-1.1` all over my system in tons of locations. But not under this specific name. So it seems clear to me that pyoxidizer is linking against something I've not actually provided in my config... I'm just not sure how to tell it to link against that!

**Comment by muthukumar-u** [comment]
if ur running on linux just make sure the ```cpython*ssl*.so``` module binary in the file system (probably in /usr/lib i guess) if it's there then u shud mention in ur ```.bzl``` to include all the extension module like ```policy.extension_module_filter = "all"```

after that make sure the ```*ssl.so``` file is in ur resource directory
