### ISSUE TITLE
build step is looking for `libcrypt.so.1`, which is called `libcrypt.so` on Fedora 30

### ISSUE THREAD

**Issue by madig** [indygreg/PyOxidizer#89]
I created a new PyOxidizer project, building fails because `libcrypt.so.1` can't be found, which is called `libcrypt.so` on Fedora 30 x86_64.

```
~/E/trufont (master|…) $ pyoxidizer init trufont
     Created binary (application) package
creating trufont/pyembed
creating trufont/pyembed/src
writing trufont/pyembed/src/config.rs
writing trufont/pyembed/src/data.rs
writing trufont/pyembed/src/importer.rs
writing trufont/pyembed/src/lib.rs
writing trufont/pyembed/src/pyalloc.rs
writing trufont/pyembed/src/pyinterp.rs
writing trufont/pyembed/src/pystr.rs
writing trufont/pyembed/Cargo.toml
writing trufont/pyembed/build.rs
writing trufont/src/main.rs
writing trufont/pyoxidizer.toml

A new Rust binary application has been created in trufont

This application can be built by doing the following:

  $ cd trufont
  $ pyoxidizer build
  $ pyoxidizer run

The default configuration is to invoke a Python REPL. You can
edit the various pyoxidizer.*.toml config files or the main.rs 
file to change behavior. The application will need to be rebuilt 
for configuration changes to take effect.
~/E/trufont (master|…) $ cd trufont/
~/E/t/trufont (master|…) $ pyoxidizer run
no existing PyOxidizer artifacts found
processing config file /home/nikolaus/Entwicklung/trufont/trufont/pyoxidizer.toml
resolving Python distribution...
downloading https://github.com/indygreg/python-build-standalone/releases/download/20190617/cpython-3.7.3-linux64-20190618T0324.tar.zst
Python distribution available at /home/nikolaus/Entwicklung/trufont/trufont/build/target/x86_64-unknown-linux-gnu/debug/pyoxidizer/cpython-3.7.3-linux64-20190618T0324.tar.zst
reading data from Python distribution...
distribution info: PythonDistributionMinimalInfo {
    flavor: "cpython",
    version: "3.7.3",
    os: "linux",
    arch: "x86_64",
    extension_modules: [
        "_abc",
        "_ast",
        "_asyncio",
        "_bisect",
        "_blake2",
        "_bz2",
        "_codecs",
        "_codecs_cn",
        "_codecs_hk",
        "_codecs_iso2022",
        "_codecs_jp",
        "_codecs_kr",
        "_codecs_tw",
        "_collections",
        "_contextvars",
        "_crypt",
        "_csv",
        "_ctypes",
        "_ctypes_test",
        "_curses",
        "_curses_panel",
        "_datetime",
        "_dbm",
        "_decimal",
        "_elementtree",
        "_functools",
        "_hashlib",
        "_heapq",
        "_imp",
        "_io",
        "_json",
        "_locale",
        "_lsprof",
        "_lzma",
        "_md5",
        "_multibytecodec",
        "_multiprocessing",
        "_opcode",
        "_operator",
        "_pickle",
        "_posixsubprocess",
        "_queue",
        "_random",
        "_sha1",
        "_sha256",
        "_sha3",
        "_sha512",
        "_signal",
        "_socket",
        "_sqlite3",
        "_sre",
        "_ssl",
        "_stat",
        "_string",
        "_struct",
        "_symtable",
        "_testbuffer",
        "_testcapi",
        "_testimportmultiple",
        "_testmultiphase",
        "_thread",
        "_tracemalloc",
        "_uuid",
        "_warnings",
        "_weakref",
        "_xxtestfuzz",
        "array",
        "atexit",
        "audioop",
        "binascii",
        "builtins",
        "cmath",
        "errno",
        "faulthandler",
        "fcntl",
        "gc",
        "grp",
        "itertools",
        "marshal",
        "math",
        "mmap",
        "nis",
        "ossaudiodev",
        "parser",
        "posix",
        "pwd",
        "pyexpat",
        "readline",
        "resource",
        "select",
        "spwd",
        "sys",
        "syslog",
        "termios",
        "time",
        "unicodedata",
        "xxlimited",
        "xxsubtype",
        "zipimport",
        "zlib",
    ],
    libraries: [
        "bz2",
        "crypto",
        "db",
        "edit",
        "ffi",
        "lzma",
        "ncurses",
        "panel",
        "readline",
        "sqlite3",
        "ssl",
        "uuid",
        "z",
    ],
    py_module_count: 1921,
}
compiling custom importlib modules to support in-memory importing
/home/nikolaus/Entwicklung/trufont/trufont/build/target/x86_64-unknown-linux-gnu/debug/pyoxidizer/python.d6b80a9723c1/python/install/bin/python3.7: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'write failed: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x556b92812353 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6485381528590a55
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x556b9280cb2b - std::sys_common::backtrace::_print::h49a82ae9552e35c7
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x556b928105f6 - std::panicking::default_hook::{{closure}}::he20974adbefcc046
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x556b92810389 - std::panicking::default_hook::he4af6af4ac7fef7b
                               at src/libstd/panicking.rs:211
   4:     0x556b92810cff - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                               at src/libstd/panicking.rs:474
   5:     0x556b92810881 - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                               at src/libstd/panicking.rs:381
   6:     0x556b92810765 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x556b9282f35c - core::panicking::panic_fmt::hc4f83bfed80aeabd
                               at src/libcore/panicking.rs:85
   8:     0x556b9220b94d - core::result::unwrap_failed::h7e072a9e1397f7de
   9:     0x556b9221b926 - <pyoxidizer::pyrepackager::bytecode::BytecodeCompiler as core::ops::drop::Drop>::drop::h286710154b25a98d
  10:     0x556b9224187b - core::ptr::real_drop_in_place::hca743aea5c168bad
  11:     0x556b922598ca - pyoxidizer::pyrepackager::repackage::process_config::h679fd9db9b20eee9
  12:     0x556b921d3123 - pyoxidizer::projectmgmt::build_pyoxidizer_artifacts::h687526b2fc0bfdf8
  13:     0x556b921d3c11 - pyoxidizer::projectmgmt::build_project::hc52e61f51abcdd5d
  14:     0x556b921d5d6b - pyoxidizer::projectmgmt::run::hd16e238a5d3cb512
  15:     0x556b92218acb - pyoxidizer::cli::run_cli::hba079ae886b00eb8
  16:     0x556b921b5211 - pyoxidizer::main::h4045261f16d3b707
  17:     0x556b9226a962 - std::rt::lang_start::{{closure}}::h68e0f031a263bf75
  18:     0x556b92810702 - std::panicking::try::do_call::hc3d8373a0b215f51
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:293
  19:     0x556b9281aef9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  20:     0x556b928112cc - std::rt::lang_start_internal::he5218c8b95d395f2
                               at src/libstd/panicking.rs:272
                               at src/libstd/panic.rs:394
                               at src/libstd/rt.rs:48
  21:     0x556b921b5311 - main
  22:     0x7fdeab001f32 - __libc_start_main
  23:     0x556b921678bd - _start
  24:                0x0 - <unknown>
thread panicked while panicking. aborting.
fish: 'pyoxidizer run' terminated by signal SIGILL (Illegale Instruktion)
```

**Comment by indygreg** [comment]
This is an interesting report!

So, when `pyoxidizer` runs, it invokes the `python` executable contained within a Python distribution in order to compile Python source to bytecode. That Python distribution is failing to run due to a missing shared library dependency (`libcrypt.so.1`). That Python distribution is produced on a Linux distro containing `libcrypt.so.1`, hence the shared library dependency.

My initial reaction to this is that Fedora _might_ be in violation of the Linux Standard Base specification, which states that `libcrypt.so.1` must exist: https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-AMD64/LSB-Core-AMD64/libcrypt.html. However, my confidence in this assessment is low, as I'm not an expert in LSB and its semantics. (My understanding is that all Linux distros _should_ implement the LSB and any interfaces defined by the LSB _should_ exist. But I'm probably wrong.)

We _might_ be able to work around this by forcing the Python distribution to link against `libcrypt.so` instead of `libcrypt.so.1`. I'll have to research this further...

**Comment by indygreg** [comment]
I found https://fedoraproject.org/wiki/Changes/FullyRemoveDeprecatedAndUnsafeFunctionsFromLibcrypt which sheds some light. There appears to be a workaround: install the `libxcrypt-compat` package.

**Comment by indygreg** [comment]
I added documentation for this issue. That's the best we can do for now. Making this problem go away is a lot more work than the _install a package_ workaround.

**Comment by madig** [comment]
That made it work. Thanks for researching this! :+1:
