### ISSUE TITLE
Error when running init - `Result::unwrap()` 

### ISSUE THREAD

**Issue by DanKremer** [indygreg/PyOxidizer#92]
Hey there,

Not sure about this error, I am new to Rust. I am on a windows machine, followed the Rust install, and the cargo install of PyOxidizer. No errors reported. When I try:

pyoxidizer init test_app

I get the following error after the \src\pystr.rs

Error:
writing trtertretre\pyembed\src\pystr.rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference \'refs/heads/master\' not found" }', src\libcore\result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

As a result no pyoxidizer.toml is created.

Any thoughts? No rush on response, not critical. Very intrigued by this project!

Dan

**Comment by indygreg** [comment]
This is an interesting bug.

How did you install PyOxidizer?

**Comment by DanKremer** [comment]
I used:
cargo install pyoxidizer

Though now that I think of it I may have doen this from the Anaconda command prompt.

**Comment by indygreg** [comment]
Could you please run `set RUST_BACKTRACE=1`, then run the failing command and paste the stack trace. I need to know which part of PyOxidizer/libgit2 is failing in order to properly debug this.

**Comment by DanKremer** [comment]
Here is the stack trace I received:

```
...\test>pyoxidizer init test_app 
     Created binary (application) package
creating test_app\pyembed
creating test_app\pyembed\src
writing test_app\pyembed\src\config.rs
writing test_app\pyembed\src\data.rs
writing test_app\pyembed\src\importer.rs
writing test_app\pyembed\src\lib.rs
writing test_app\pyembed\src\pyalloc.rs
writing test_app\pyembed\src\pyinterp.rs
writing test_app\pyembed\src\pystr.rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference \'refs/heads/master\' not found" }', src\libcore\result.rs:999:5
stack backtrace:
   0: git_packbuilder_object_count
   1: git_packbuilder_object_count
   2: git_packbuilder_object_count
   3: git_packbuilder_object_count
   4: git_packbuilder_object_count
   5: git_packbuilder_object_count
   6: git_packbuilder_object_count
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: git_packbuilder_object_count
  16: git_packbuilder_object_count
  17: git_packbuilder_object_count
  18: <unknown>
  19: git_odb_object_id
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
```

**Comment by kurt-rhee** [comment]
I have the same issue on Windows, installed via CMD
