### ISSUE TITLE
ModuleNotFoundError: How to configure my project so the primary module with a main function is found?

### ISSUE THREAD

**Issue by monocongo** [indygreg/PyOxidizer#99]
My goal is to build a single file executable that I can distribute to users so they don't need to worry about installing Python or anything else in order to run my code.

I have built my first project with PyOxidizer but when I attempt to run it (initial testing on the same system where it was built) I get a `ModuleNotFoundError`.

The project's repository structure looks like this (some non-consequential files have been ommitted for brevity):
```
myproj  # top-level of the repository
|
+-- myproj  # primary module of the project
      |
      +-- __init__.py
      +-- __main__.py
      +-- submodule1.py
      +-- submodule2.py
+-- pyembed  # added by PyOxidizer
+-- src  # added by PyOxidizer
+-- license.txt
+-- pyoxidizer.toml
+-- README.md
+-- requirements.txt
+-- setup.py
```

The file `myproj.__main__.py` contains a `main` function where most of the action happens, and with that function are calls to a few of the functions defined within the submodule files. The `myproj.__main__.py` file looks like this:
```
def main():
    # lots of code here

if __name__ == "__main__":
    main()
```

Below are the uncommented parts of the `pyoxidizer.toml` file:
```
[[build]]
application_name = "deep_monitor"

[[embedded_python_config]]
raw_allocator = "jemalloc"

[[embedded_python_config]]
build_target = "x86_64-pc-windows-msvc"
raw_allocator = "system"

[[packaging_rule]]
type = "stdlib-extensions-policy"
policy = "all"

[[packaging_rule]]
type = "stdlib"
include_source = false

[[packaging_rule]]
type = "write-license-files"
path = ""

[[packaging_rule]]
type = "package-root"
path = "myproj"
packages = ["myproj"]

[[embedded_python_run]]
mode = "module"
module = "myproj.__main__"
```

I have built the project apparently without error, but when I run it I see this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'myproj'
```

BTW I get the same error if I instead use the following `embedded _python_run` setting within the `pyoxidizer.toml` file:
```
mode = "eval"
code = "from myproj.__main__ import main; main()"
```
Can anyone advise as to how I can overcome this issue, and/or if I should be doing things in a different manner? Maybe I need to somehow install the `myproj` module into the Python environment?

Thanks in advance for any suggestions or assistance. And thanks also to the creator and contributors on this project, it looks like it will be quite useful once I work out how to use it correctly.

**Comment by gnprice** [comment]
> [[packaging_rule]]
> type = "package-root"
> path = "myproj"
> packages = ["myproj"]

I think you want `path = "."`. The packages are found relative to the path, which seems to be relative to the root of the project where the `pyoxidizer.toml` file is located.

You might find helpful a pair of small examples I made yesterday when playing around with this tool:
https://github.com/indygreg/PyOxidizer/issues/78#issuecomment-511657412

---

One useful thing `pyoxidizer` could perhaps do is to give an error at build time if a given `packaging_rule` (or even a given package in a `package-root` rule) finds nothing at all. Perhaps something narrower than that -- not sure what situations might exist where that's normal and an error would be annoying -- but I think a condition like that would help in cases like this one.

**Comment by monocongo** [comment]
Thanks for your help, @gnprice . Your answer is correct and got me over this hump.

I now see errors involving not being able to find imported third party modules, for example:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "myproj", line 1, in <module>
  File "myproj.__main__", line 8, in <module>
ModuleNotFoundError: No module named 'cv2'
```

My assumption is that this means I haven't configured PyOxidizer to build and include a Python interpreter with my project's required dependencies, such as OpenCV in this case. To rectify this I've built a virtual environment based upon my project's `requirements.txt` and used that for the "virtualenv" packaging rule within `pyoxidizer.toml`:
```
[[packaging_rule]]
type = "virtualenv"
path = "/home/james/.virtualenvs/myproj_venv"
```

This results in a build error from PyOxidizer:
```
processing packaging rule: Virtualenv(PackagingVirtualenv { path: "/home/james/.virtualenvs/myproj_venv", optimize_level: 0, excludes: [], include_source: true, install_location: Embedded })
thread 'main' panicked at 'unable to get directory entry: Error { depth: 0, inner: Io { path: Some("/home/james/.virtualenvs/myproj_venv/lib/python3.7/site-packages"), err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/libcore/result.rs:1009:5
```
My read of the above is that PyOxidizer is expecting a Python virtual environment at version 3.7, and my project requires version 3.6, and this is the version used for the virtual environment I've created:
```
$ ll /home/james/.virtualenvs/myproj_venv/lib/
total 12K
drwxr-xr-x 3 james james 4.0K Jul 17 09:15 ./
drwxr-xr-x 5 james james 4.0K Jul 17 09:15 ../
drwxr-xr-x 5 james james 4.0K Jul 17 09:15 python3.6/
```
This appears to be a show stopper unless I manage to remove whatever dependency I have in my project that's forcing me down to Python version 3.6, correct?

**Comment by gnprice** [comment]
Great!

> My assumption is that this means I haven't configured PyOxidizer to build and include a Python interpreter containing all my project's required dependencies, such as OpenCV in this case. To rectify this I've built a virtual environment based upon my project's `requirements.txt` and used that for the "virtualenv" packaging rule within `pyoxidizer.toml`:
> 
> ```
> [[packaging_rule]]
> type = "virtualenv"
> path = "/home/james/.virtualenvs/myproj_venv"
> ```

Have you tried doing it with `type = "pip-install-simple"`? That's what I did in the second of the examples linked above.

That will put the build/install process for the dependency inside PyOxidizer's control, which I think is likely to be something you need. OpenCV sounds like something that probably involves an extension module; and just like the Python interpreter itself, those require some adjustments to how they're built:
https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#c-and-other-native-extension-modules
https://pyoxidizer.readthedocs.io/en/latest/status.html#status-extension-modules
which PyOxidizer will attempt to make when building under `pip-install-simple`.
